/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.OkotaArea;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author chinex
 */
public class Admin extends javax.swing.JPanel {

    /**
     * Creates new form Admin
     */
    Membership mem;
 private final HomeFront front; 
 private final HomePanel  home; 
 DBOperations db = new DBOperations();
 private String word= null;
    public Admin(HomeFront front, HomePanel  home) {
        initComponents();
        this.front = front;
        this.home = home;
        
        NewInExRegPanel.setVisible(false);
        ViewInExRegPanel.setVisible(false);
        AllnExRegPanel.setVisible(false);
        FinancialStatementPanel.setVisible(false);
                viewinExAmtTextField.setVisible(false);
                viewInScrollpane.setVisible(false);
                viewInScrollpane1.setVisible(false);
                viewinExAmtinwordsTextField.setVisible(false);
                viewinExLocTextArea.setVisible(false);
                viewinExsaveButton.setVisible(false);
                viewinExdescTextField.setVisible(false);
                naira.setVisible(false);
        textCustomise("Enter Amount", inExAmtTextField);
        textCustomise1("Enter Present Location", inExLocTextArea);
        textCustomise("Enter Description", inExdescTextField);
        textCustomise1("Enter Amount in Words", inExAmtinwordsTextField);
        
    }
private void textCustomise(String text, JTextField component)
    {
        PromptSupport.setPrompt(text, component);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.HIDE_PROMPT, component);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, component);
        PromptSupport.setFontStyle(Font.BOLD, component);
        PromptSupport.setForeground(Color.darkGray, component);
    }
private void textCustomise1(String text, JTextArea component)
    {
        PromptSupport.setPrompt(text, component);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.HIDE_PROMPT, component);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, component);
        PromptSupport.setFontStyle(Font.BOLD, component);
        PromptSupport.setForeground(Color.darkGray, component);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        AdminHomePanel = new javax.swing.JPanel();
        adminBackbutton = new javax.swing.JButton();
        AreaIncomeLabel = new javax.swing.JLabel();
        EditAreaIncomeLabel = new javax.swing.JLabel();
        AreaExpenditureLabel = new javax.swing.JLabel();
        AllAreaIncome = new javax.swing.JLabel();
        AllAreaExpenditureLabel = new javax.swing.JLabel();
        AreaFinancialStatement = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EditAreaExpenditureLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        BackgroundPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        NewInExRegPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        inExdescTextField = new javax.swing.JTextField();
        inExDateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        inExLocTextArea = new javax.swing.JTextArea();
        inExAmtTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inExsaveButton = new javax.swing.JButton();
        inExLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inExAmtinwordsTextField = new javax.swing.JTextArea();
        ViewInExRegPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        viewinExsaveButton = new javax.swing.JButton();
        viewinExLabel = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        viewINexTable = new javax.swing.JTable();
        viewinExdescTextField = new javax.swing.JTextField();
        viewinExAmtTextField = new javax.swing.JTextField();
        naira = new javax.swing.JLabel();
        viewInScrollpane = new javax.swing.JScrollPane();
        viewinExAmtinwordsTextField = new javax.swing.JTextArea();
        viewInScrollpane1 = new javax.swing.JScrollPane();
        viewinExLocTextArea = new javax.swing.JTextArea();
        viewinExDateChooser = new com.toedter.calendar.JDateChooser();
        viewinExsearchButton = new javax.swing.JButton();
        AllnExRegPanel = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        AllINexTable = new javax.swing.JTable();
        AllInExLabel = new javax.swing.JLabel();
        FinancialStatementPanel = new javax.swing.JPanel();
        finStaTODateChooser = new com.toedter.calendar.JDateChooser();
        finStaFROMDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(146, 198, 227));
        setForeground(new java.awt.Color(146, 198, 227));

        adminBackbutton.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        adminBackbutton.setText("BACK");
        adminBackbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBackbuttonActionPerformed(evt);
            }
        });

        AreaIncomeLabel.setBackground(new java.awt.Color(51, 51, 51));
        AreaIncomeLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        AreaIncomeLabel.setForeground(new java.awt.Color(51, 51, 51));
        AreaIncomeLabel.setText("New Income");
        AreaIncomeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AreaIncomeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AreaIncomeLabelMouseEntered(evt);
            }
        });

        EditAreaIncomeLabel.setBackground(new java.awt.Color(51, 51, 51));
        EditAreaIncomeLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        EditAreaIncomeLabel.setForeground(new java.awt.Color(51, 51, 51));
        EditAreaIncomeLabel.setText("View Income");
        EditAreaIncomeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditAreaIncomeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AreaIncomeLabelMouseEntered(evt);
            }
        });

        AreaExpenditureLabel.setBackground(new java.awt.Color(51, 51, 51));
        AreaExpenditureLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        AreaExpenditureLabel.setForeground(new java.awt.Color(51, 51, 51));
        AreaExpenditureLabel.setText("New Expenditure");
        AreaExpenditureLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AreaExpenditureLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AreaIncomeLabelMouseEntered(evt);
            }
        });

        AllAreaIncome.setBackground(new java.awt.Color(51, 51, 51));
        AllAreaIncome.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        AllAreaIncome.setForeground(new java.awt.Color(51, 51, 51));
        AllAreaIncome.setText("All Income");
        AllAreaIncome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllAreaIncomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AreaIncomeLabelMouseEntered(evt);
            }
        });

        AllAreaExpenditureLabel.setBackground(new java.awt.Color(51, 51, 51));
        AllAreaExpenditureLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        AllAreaExpenditureLabel.setForeground(new java.awt.Color(51, 51, 51));
        AllAreaExpenditureLabel.setText("All Expenditure");
        AllAreaExpenditureLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllAreaExpenditureLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AreaIncomeLabelMouseEntered(evt);
            }
        });

        AreaFinancialStatement.setBackground(new java.awt.Color(51, 51, 51));
        AreaFinancialStatement.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        AreaFinancialStatement.setForeground(new java.awt.Color(51, 51, 51));
        AreaFinancialStatement.setText("Financial Statement");
        AreaFinancialStatement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AreaFinancialStatementMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AreaIncomeLabelMouseEntered(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/OkotaArea/logo smallsma.png"))); // NOI18N
        jLabel1.setToolTipText("");

        EditAreaExpenditureLabel.setBackground(new java.awt.Color(51, 51, 51));
        EditAreaExpenditureLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        EditAreaExpenditureLabel.setForeground(new java.awt.Color(51, 51, 51));
        EditAreaExpenditureLabel.setText("View Expenditure");
        EditAreaExpenditureLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditAreaExpenditureLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AreaIncomeLabelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout AdminHomePanelLayout = new javax.swing.GroupLayout(AdminHomePanel);
        AdminHomePanel.setLayout(AdminHomePanelLayout);
        AdminHomePanelLayout.setHorizontalGroup(
            AdminHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EditAreaIncomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AreaExpenditureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
            .addComponent(AllAreaIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AllAreaExpenditureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AreaFinancialStatement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(EditAreaExpenditureLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AreaIncomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addComponent(jSeparator5)
            .addComponent(jSeparator7)
            .addComponent(jSeparator8)
            .addComponent(jSeparator2)
            .addGroup(AdminHomePanelLayout.createSequentialGroup()
                .addGroup(AdminHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminHomePanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(adminBackbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AdminHomePanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
            .addComponent(jSeparator6)
        );
        AdminHomePanelLayout.setVerticalGroup(
            AdminHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminHomePanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AreaIncomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditAreaIncomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AreaExpenditureLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditAreaExpenditureLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AllAreaIncome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AllAreaExpenditureLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AreaFinancialStatement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(adminBackbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BackgroundPanel.setBackground(new java.awt.Color(146, 198, 227));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/OkotaArea/DC Wallpaper101.png"))); // NOI18N

        NewInExRegPanel.setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        inExdescTextField.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N

        inExLocTextArea.setColumns(20);
        inExLocTextArea.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        inExLocTextArea.setRows(5);
        jScrollPane1.setViewportView(inExLocTextArea);

        inExAmtTextField.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("₦");

        inExsaveButton.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        inExsaveButton.setText("SAVE");
        inExsaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inExsaveButtonActionPerformed(evt);
            }
        });

        inExLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        inExLabel.setForeground(new java.awt.Color(102, 102, 102));

        inExAmtinwordsTextField.setColumns(20);
        inExAmtinwordsTextField.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        inExAmtinwordsTextField.setRows(5);
        jScrollPane2.setViewportView(inExAmtinwordsTextField);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(inExsaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(283, 283, 283))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(inExAmtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(inExDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(inExdescTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(inExLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inExLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inExDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(inExdescTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inExAmtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(inExsaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout NewInExRegPanelLayout = new javax.swing.GroupLayout(NewInExRegPanel);
        NewInExRegPanel.setLayout(NewInExRegPanelLayout);
        NewInExRegPanelLayout.setHorizontalGroup(
            NewInExRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewInExRegPanelLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        NewInExRegPanelLayout.setVerticalGroup(
            NewInExRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewInExRegPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        ViewInExRegPanel.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        viewinExsaveButton.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        viewinExsaveButton.setText("SAVE");
        viewinExsaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewinExsaveButtonActionPerformed(evt);
            }
        });

        viewinExLabel.setFont(new java.awt.Font("Bell MT", 1, 40)); // NOI18N
        viewinExLabel.setForeground(new java.awt.Color(51, 51, 51));
        viewinExLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        viewINexTable.setBackground(new java.awt.Color(51, 51, 51));
        viewINexTable.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        viewINexTable.setForeground(new java.awt.Color(255, 255, 255));
        viewINexTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Amount", "Amt_in_Words", "Describtion", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        viewINexTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewINexTableMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(viewINexTable);

        viewinExdescTextField.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N

        viewinExAmtTextField.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N

        naira.setBackground(new java.awt.Color(255, 255, 255));
        naira.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        naira.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        naira.setText("₦");

        viewinExAmtinwordsTextField.setColumns(20);
        viewinExAmtinwordsTextField.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        viewinExAmtinwordsTextField.setRows(5);
        viewInScrollpane.setViewportView(viewinExAmtinwordsTextField);

        viewinExLocTextArea.setColumns(20);
        viewinExLocTextArea.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        viewinExLocTextArea.setRows(5);
        viewInScrollpane1.setViewportView(viewinExLocTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewInScrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewinExdescTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewInScrollpane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(naira, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewinExAmtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(viewinExLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(326, 326, 326)
                                .addComponent(viewinExsaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 53, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewinExLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewinExdescTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viewinExAmtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(naira, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewInScrollpane1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(viewInScrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewinExsaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        viewinExsearchButton.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        viewinExsearchButton.setText("SEARCH");
        viewinExsearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewinExsearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewInExRegPanelLayout = new javax.swing.GroupLayout(ViewInExRegPanel);
        ViewInExRegPanel.setLayout(ViewInExRegPanelLayout);
        ViewInExRegPanelLayout.setHorizontalGroup(
            ViewInExRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewInExRegPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewinExDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(viewinExsearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310))
            .addGroup(ViewInExRegPanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        ViewInExRegPanelLayout.setVerticalGroup(
            ViewInExRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewInExRegPanelLayout.createSequentialGroup()
                .addGroup(ViewInExRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewInExRegPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(viewinExsearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewInExRegPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(viewinExDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        AllINexTable.setBackground(new java.awt.Color(51, 51, 51));
        AllINexTable.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        AllINexTable.setForeground(new java.awt.Color(255, 255, 255));
        AllINexTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Amount", "Amt_in_Words", "Describtion", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AllINexTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllINexTableMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(AllINexTable);

        AllInExLabel.setFont(new java.awt.Font("Bell MT", 1, 40)); // NOI18N
        AllInExLabel.setForeground(new java.awt.Color(51, 51, 51));
        AllInExLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout AllnExRegPanelLayout = new javax.swing.GroupLayout(AllnExRegPanel);
        AllnExRegPanel.setLayout(AllnExRegPanelLayout);
        AllnExRegPanelLayout.setHorizontalGroup(
            AllnExRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AllnExRegPanelLayout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addComponent(AllInExLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addComponent(jScrollPane11)
        );
        AllnExRegPanelLayout.setVerticalGroup(
            AllnExRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllnExRegPanelLayout.createSequentialGroup()
                .addComponent(AllInExLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE))
        );

        finStaTODateChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finStaTODateChooserMouseClicked(evt);
            }
        });

        finStaFROMDateChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finStaFROMDateChooserMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel6.setText("Requesting Financial Statement...........");

        jLabel7.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel7.setText("From");

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("To");

        javax.swing.GroupLayout FinancialStatementPanelLayout = new javax.swing.GroupLayout(FinancialStatementPanel);
        FinancialStatementPanel.setLayout(FinancialStatementPanelLayout);
        FinancialStatementPanelLayout.setHorizontalGroup(
            FinancialStatementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FinancialStatementPanelLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finStaFROMDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finStaTODateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(FinancialStatementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FinancialStatementPanelLayout.setVerticalGroup(
            FinancialStatementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinancialStatementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(FinancialStatementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(finStaTODateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(finStaFROMDateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(695, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 985, Short.MAX_VALUE)
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NewInExRegPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ViewInExRegPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AllnExRegPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FinancialStatementPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NewInExRegPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ViewInExRegPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AllnExRegPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FinancialStatementPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(AdminHomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adminBackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBackbuttonActionPerformed
        // TODO add your handling code here:
        front.updatePanel(home);
    }//GEN-LAST:event_adminBackbuttonActionPerformed

    private void AreaIncomeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AreaIncomeLabelMouseClicked
        // TODO add your handling code here:
             NewInExRegPanel.setVisible(true);
             NewupdatePanel(NewInExRegPanel);
             inExLabel.setText("ENTER INCOME DETAILS");
    }//GEN-LAST:event_AreaIncomeLabelMouseClicked

    private void AreaExpenditureLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AreaExpenditureLabelMouseClicked
        // TODO add your handling code here:
             NewInExRegPanel.setVisible(true);
             NewupdatePanel(NewInExRegPanel);
             inExLabel.setText("ENTER EXPENDITURE DETAILS");
    }//GEN-LAST:event_AreaExpenditureLabelMouseClicked

    private void EditAreaExpenditureLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditAreaExpenditureLabelMouseClicked
        // TODO add your handling code here:
             ViewInExRegPanel.setVisible(true);
             NewupdatePanel(ViewInExRegPanel);
             viewinExLabel.setText("Expenditure");
    }//GEN-LAST:event_EditAreaExpenditureLabelMouseClicked

    private void AllAreaIncomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllAreaIncomeMouseClicked
        // TODO add your handling code here:
             AllnExRegPanel.setVisible(true);
             NewupdatePanel(AllnExRegPanel);
             AllInExLabel.setText("All Area Income");                   
                    HashMap<String, String[]> objMap = db.AllAreaIn();
                    TabularRecordUpdater up = new TabularRecordUpdater(objMap,this);
                    up.populateAllInExTable(objMap);
    }//GEN-LAST:event_AllAreaIncomeMouseClicked

    private void AllAreaExpenditureLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllAreaExpenditureLabelMouseClicked
        // TODO add your handling code here:
             AllnExRegPanel.setVisible(true);
             NewupdatePanel(AllnExRegPanel);
             AllInExLabel.setText("All Area Expenditure");
                    HashMap<String, String[]> objMap = db.AllAreaEx();
                    TabularRecordUpdater up = new TabularRecordUpdater(objMap,this);
                    up.populateAllInExTable(objMap);
    }//GEN-LAST:event_AllAreaExpenditureLabelMouseClicked

    private void AreaFinancialStatementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AreaFinancialStatementMouseClicked
        // TODO add your handling code here:
             FinancialStatementPanel.setVisible(true);
             NewupdatePanel(FinancialStatementPanel);
    }//GEN-LAST:event_AreaFinancialStatementMouseClicked

    private void inExsaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inExsaveButtonActionPerformed
        // TODO add your handling code here:
          
          SimpleDateFormat sFormat = new SimpleDateFormat("yyyy-MM-dd");
                Date datess = inExDateChooser.getDate();
                String dates = sFormat.format(datess);
                String date = MonthConverter(dates);
                
          String amt= inExAmtTextField.getText();      
          String desc= inExdescTextField.getText();
          String loc = inExLocTextArea.getText();
          String amtW = inExAmtinwordsTextField.getText();
          if("ENTER INCOME DETAILS".equals(inExLabel.getText()))
          {
           db.incomesave(amt,date,desc,loc,amtW);
           inExAmtTextField.setText("");
           inExAmtinwordsTextField.setText("");
           inExLocTextArea.setText("");
           inExdescTextField.setText("");
           inExDateChooser.setDate(null);
          }
          else if ("ENTER EXPENDITURE DETAILS".equals(inExLabel.getText()) )
          {
           db.Expensave(amt,date,desc,loc,amtW);
           inExAmtTextField.setText("");
           inExAmtinwordsTextField.setText("");
           inExLocTextArea.setText("");
           inExdescTextField.setText("");
           inExDateChooser.setDate(null);
          }
    }//GEN-LAST:event_inExsaveButtonActionPerformed

    private void viewinExsaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewinExsaveButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sFormat = new SimpleDateFormat("yyyy-MM-dd");   
                Date datess = viewinExDateChooser.getDate();
                String dates = sFormat.format(datess);
                String date = MonthConverter(dates);    
                       
        if      ("Income".equals(viewinExLabel.getText()))
          {                   
                 String in = viewinExAmtTextField.getText();
                 String loc =viewinExLocTextArea.getText();
                 String des =viewinExdescTextField.getText();
                 String aw =viewinExAmtinwordsTextField.getText();
                 db.incomesave1(in, date, des, loc, aw,word);
          }
        else if ("Expenditure".equals(viewinExLabel.getText()))
          {
                 String ex = viewinExAmtTextField.getText();
                 String loc =viewinExLocTextArea.getText();
                 String des =viewinExdescTextField.getText();
                 String aw =viewinExAmtinwordsTextField.getText();
                 db.Expensave1(ex, date, des, loc, aw,word);
          }    
    }//GEN-LAST:event_viewinExsaveButtonActionPerformed

    public JTable getViewINexTable() {
        return viewINexTable;
    }

    public JTable getAllINexTable() {
        return AllINexTable;
    }

    private void viewinExsearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewinExsearchButtonActionPerformed
        // TODO add your handling code here:
          SimpleDateFormat sFormat = new SimpleDateFormat("yyyy-MM-dd");   
                Date datess = viewinExDateChooser.getDate();
                String dates = sFormat.format(datess);
                String date = MonthConverter(dates);
                
                if ("Income".equals(viewinExLabel.getText()))
                {                   
                    HashMap<String, String[]> objMap = db.viewoneincome(date);
                    TabularRecordUpdater up = new TabularRecordUpdater(objMap,this);
                    up.populateOneInExTable(objMap);
                    
                }
               else if ("Expenditure".equals(viewinExLabel.getText()))
                {
                    HashMap<String, String[]> objMap = db.viewoneExp(date);
                    TabularRecordUpdater up = new TabularRecordUpdater(objMap,this);
                    up.populateOneInExTable(objMap);
                }    
    }//GEN-LAST:event_viewinExsearchButtonActionPerformed

    private void viewINexTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewINexTableMouseClicked
        // TODO add your handling code here:
        viewINexTable.setRowSelectionAllowed(true);
        int row = viewINexTable.getSelectedRow();
        String rowword = (String) viewINexTable.getValueAt(row, 0);
        this.word = rowword;
        Map <String, String> rst = db.getInExView(rowword);
        String aw= rst.get("aw");String in= rst.get("in"); String ex= rst.get("ex"); String des= rst.get("des"); String loc= rst.get("loc");
     
viewinExAmtTextField.setVisible(true);viewInScrollpane.setVisible(true);viewInScrollpane1.setVisible(true);viewinExAmtinwordsTextField.setVisible(true);
viewinExLocTextArea.setVisible(true);viewinExsaveButton.setVisible(true);viewinExdescTextField.setVisible(true); naira.setVisible(true);
                
               if ("Income".equals(viewinExLabel.getText()))
                {                   
                  viewinExAmtTextField.setText(in);
                  viewinExLocTextArea.setText(loc);
                  viewinExdescTextField.setText(des);
                  viewinExAmtinwordsTextField.setText(aw);
                }
                else if ("Expenditure".equals(viewinExLabel.getText()))
                {
                  viewinExAmtTextField.setText(ex);
                  viewinExLocTextArea.setText(loc);
                  viewinExdescTextField.setText(des);
                  viewinExAmtinwordsTextField.setText(aw);
                }    
    }//GEN-LAST:event_viewINexTableMouseClicked

    private void AllINexTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllINexTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AllINexTableMouseClicked

    private String MonthConverter(String dates)
{
  String mont = dates.substring(5, 7);String Months=null;String year = dates.substring(0,4);String days = dates.substring(9,10);
                int monte = Integer.parseInt(mont);
                int months = Integer.parseInt(mont.substring(1));
                        if(months==1){Months="January";}
                        else if(months==2){Months="February";}
                        else if(months==3){Months="March";}
                        else if(months==4){Months="April";}
                        else if(months==5){Months="May";}
                        else if(months==6){Months="June";}
                        else if(months==7){Months="July";}
                        else if(months==8){Months="August";}
                        else if(months==9){Months="September";}
                        else if(monte==10){Months="October";}
                        else if(monte==11){Months="November";}
                        else if(monte==12){Months="December";}
                String date = year+" "+ Months + " " + days ; 
                return date;
}
    private void finStaTODateChooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finStaTODateChooserMouseClicked
        // TODO add your handling code here:
        SimpleDateFormat sFormat = new SimpleDateFormat("yyyy-MM-dd");   
        Date stadatess = finStaTODateChooser.getDate();Date enddatess = finStaTODateChooser.getDate();
        String stadate = sFormat.format(stadatess);String enddates = sFormat.format(enddatess);
        String statdate = MonthConverter(stadate);String enddate = MonthConverter(enddates);        
    }//GEN-LAST:event_finStaTODateChooserMouseClicked

    private void finStaFROMDateChooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finStaFROMDateChooserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_finStaFROMDateChooserMouseClicked

    private void AreaIncomeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AreaIncomeLabelMouseEntered
        // TODO add your handling code here:
            Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
            Object obj = evt.getSource();
            JLabel lb = (JLabel) obj;
            lb.setCursor(handCursor);
    }//GEN-LAST:event_AreaIncomeLabelMouseEntered

    private void EditAreaIncomeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditAreaIncomeLabelMouseClicked
        // TODO add your handling code here:
             ViewInExRegPanel.setVisible(true);
             NewupdatePanel(ViewInExRegPanel);
             viewinExLabel.setText("Income");
    }//GEN-LAST:event_EditAreaIncomeLabelMouseClicked
public void NewupdatePanel (JPanel currentPanel)
    {
        BackgroundPanel.removeAll();   
        GroupLayout l = (GroupLayout) BackgroundPanel.getLayout();   
        l.setHorizontalGroup(
            l.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        l.setVerticalGroup(
            l.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminHomePanel;
    private javax.swing.JLabel AllAreaExpenditureLabel;
    private javax.swing.JLabel AllAreaIncome;
    private javax.swing.JTable AllINexTable;
    private javax.swing.JLabel AllInExLabel;
    private javax.swing.JPanel AllnExRegPanel;
    private javax.swing.JLabel AreaExpenditureLabel;
    private javax.swing.JLabel AreaFinancialStatement;
    private javax.swing.JLabel AreaIncomeLabel;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel EditAreaExpenditureLabel;
    private javax.swing.JLabel EditAreaIncomeLabel;
    private javax.swing.JPanel FinancialStatementPanel;
    private javax.swing.JPanel NewInExRegPanel;
    private javax.swing.JPanel ViewInExRegPanel;
    private javax.swing.JButton adminBackbutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser finStaFROMDateChooser;
    private com.toedter.calendar.JDateChooser finStaTODateChooser;
    private javax.swing.JTextField inExAmtTextField;
    private javax.swing.JTextArea inExAmtinwordsTextField;
    private com.toedter.calendar.JDateChooser inExDateChooser;
    private javax.swing.JLabel inExLabel;
    private javax.swing.JTextArea inExLocTextArea;
    private javax.swing.JTextField inExdescTextField;
    private javax.swing.JButton inExsaveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel naira;
    private javax.swing.JTable viewINexTable;
    private javax.swing.JScrollPane viewInScrollpane;
    private javax.swing.JScrollPane viewInScrollpane1;
    private javax.swing.JTextField viewinExAmtTextField;
    private javax.swing.JTextArea viewinExAmtinwordsTextField;
    private com.toedter.calendar.JDateChooser viewinExDateChooser;
    private javax.swing.JLabel viewinExLabel;
    private javax.swing.JTextArea viewinExLocTextArea;
    private javax.swing.JTextField viewinExdescTextField;
    private javax.swing.JButton viewinExsaveButton;
    private javax.swing.JButton viewinExsearchButton;
    // End of variables declaration//GEN-END:variables
}
