/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.OkotaArea;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author chinex
 */
 
public class AreaReport extends javax.swing.JPanel {

    /**
     * Creates new form AreaReport
     */
 private final HomeFront front; 
 private final HomePanel  home;
 DBOperations db = new DBOperations();
    public AreaReport(HomeFront front, HomePanel  home) {
        initComponents();
        this.front = front;
        this.home = home;
        NewAreaReportPanel.setVisible(false);
        AllAreaReportPanel.setVisible(false);
        EditAreaReportPanel.setVisible(false);
        textCustomise("Enter Total Target", Totaltargetmembership);
        textCustomise("Enter Total Membership", TotalareamemberTF);
        textCustomise("Enter No of Cells", TotalAreaCellTF);
        textCustomise("Enter Cells Held", NumberofHeldcellTF);
        textCustomise("How Many New Cells", newCellTF);
        textCustomise("Cell Attendance", CellattendTF);
        textCustomise("Enter Number Attended Sunday Service", SundayAttendTF);
        textCustomise("Enter Number of Previous MVPs", PreviousMVPTF);
        textCustomise("Enter Number of MVPs", NewMVPTF);
        textCustomise("Enter Number of 2nd Timers", secondTimerTF);
        textCustomise("Total Joined Workforce", JoindWorkTF);
        textCustomise("Total Went On Outreach", OutreachTF);
        textCustomise("Total Attended DCA Basic", DcabasicTF);
        textCustomise("Total Attended DCA Maturity", dcaMatTF);
        textCustomise("Total Attended Encounter", EncTF);
        textCustomise("Total Attended DLI", DLITF);
        textCustomise("Enter Number Of Visits", VisitTF);
        textCustomise("Enter Number of Calls", CallsTF);
    }
private void textCustomise(String text, JTextField component)
    {
        PromptSupport.setPrompt(text, component);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.HIDE_PROMPT, component);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, component);
        PromptSupport.setFontStyle(Font.BOLD, component);
        PromptSupport.setForeground(Color.darkGray, component);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaReportHomePanel = new javax.swing.JPanel();
        areareportBackbutton = new javax.swing.JButton();
        NewReportLabel = new javax.swing.JLabel();
        ViewReportLabel = new javax.swing.JLabel();
        AllReportLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        BackgroundPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NewAreaReportPanel = new javax.swing.JPanel();
        reportDateChooser = new com.toedter.calendar.JDateChooser();
        Totaltargetmembership = new javax.swing.JTextField();
        TotalareamemberTF = new javax.swing.JTextField();
        TotalAreaCellTF = new javax.swing.JTextField();
        SundayAttendTF = new javax.swing.JTextField();
        secondTimerTF = new javax.swing.JTextField();
        DcabasicTF = new javax.swing.JTextField();
        DLITF = new javax.swing.JTextField();
        VisitTF = new javax.swing.JTextField();
        dcaMatTF = new javax.swing.JTextField();
        JoindWorkTF = new javax.swing.JTextField();
        PreviousMVPTF = new javax.swing.JTextField();
        NumberofHeldcellTF = new javax.swing.JTextField();
        CallsTF = new javax.swing.JTextField();
        EncTF = new javax.swing.JTextField();
        OutreachTF = new javax.swing.JTextField();
        NewMVPTF = new javax.swing.JTextField();
        CellattendTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        reportSaveButton = new javax.swing.JButton();
        newCellTF = new javax.swing.JTextField();
        AllAreaReportPanel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        AllareareportTable = new javax.swing.JTable();
        EditAreaReportPanel = new javax.swing.JPanel();
        EditreportSearchSaveButton = new javax.swing.JButton();
        editreportlabel = new javax.swing.JLabel();
        EditreportDateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane9 = new javax.swing.JScrollPane();
        EditareareportTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(146, 198, 227));

        areareportBackbutton.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        areareportBackbutton.setText("BACK");
        areareportBackbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areareportBackbuttonActionPerformed(evt);
            }
        });

        NewReportLabel.setBackground(new java.awt.Color(51, 51, 51));
        NewReportLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        NewReportLabel.setForeground(new java.awt.Color(51, 51, 51));
        NewReportLabel.setText("New Report");
        NewReportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewReportLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewReportLabelMouseEntered(evt);
            }
        });

        ViewReportLabel.setBackground(new java.awt.Color(51, 51, 51));
        ViewReportLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        ViewReportLabel.setForeground(new java.awt.Color(51, 51, 51));
        ViewReportLabel.setText("View Report");
        ViewReportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewReportLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewReportLabelMouseEntered(evt);
            }
        });

        AllReportLabel.setBackground(new java.awt.Color(51, 51, 51));
        AllReportLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        AllReportLabel.setForeground(new java.awt.Color(51, 51, 51));
        AllReportLabel.setText("All Report");
        AllReportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllReportLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewReportLabelMouseEntered(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/OkotaArea/logo smallsma.png"))); // NOI18N
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout AreaReportHomePanelLayout = new javax.swing.GroupLayout(AreaReportHomePanel);
        AreaReportHomePanel.setLayout(AreaReportHomePanelLayout);
        AreaReportHomePanelLayout.setHorizontalGroup(
            AreaReportHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AllReportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ViewReportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NewReportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(AreaReportHomePanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(areareportBackbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreaReportHomePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        AreaReportHomePanelLayout.setVerticalGroup(
            AreaReportHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreaReportHomePanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(NewReportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewReportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AllReportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(areareportBackbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        BackgroundPanel.setBackground(new java.awt.Color(146, 198, 227));
        BackgroundPanel.setForeground(new java.awt.Color(102, 153, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/OkotaArea/DC Wallpaper101.png"))); // NOI18N

        Totaltargetmembership.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        TotalareamemberTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        TotalAreaCellTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        SundayAttendTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        secondTimerTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        DcabasicTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        DLITF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        VisitTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        dcaMatTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        JoindWorkTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        PreviousMVPTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        NumberofHeldcellTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        CallsTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        EncTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        OutreachTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        NewMVPTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        CellattendTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ENTER REPORT DETAILS");

        reportSaveButton.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        reportSaveButton.setText("SAVE");
        reportSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportSaveButtonActionPerformed(evt);
            }
        });

        newCellTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        javax.swing.GroupLayout NewAreaReportPanelLayout = new javax.swing.GroupLayout(NewAreaReportPanel);
        NewAreaReportPanel.setLayout(NewAreaReportPanelLayout);
        NewAreaReportPanelLayout.setHorizontalGroup(
            NewAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewAreaReportPanelLayout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(reportSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(NewAreaReportPanelLayout.createSequentialGroup()
                .addGroup(NewAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewAreaReportPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(NewAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(NewAreaReportPanelLayout.createSequentialGroup()
                                .addGroup(NewAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reportDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(secondTimerTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SundayAttendTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DcabasicTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DLITF, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(NewAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Totaltargetmembership, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(VisitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PreviousMVPTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JoindWorkTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dcaMatTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(NewAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalareamemberTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CallsTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NewMVPTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(OutreachTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EncTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(NewAreaReportPanelLayout.createSequentialGroup()
                                .addComponent(TotalAreaCellTF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(NumberofHeldcellTF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(CellattendTF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(newCellTF))))
                    .addGroup(NewAreaReportPanelLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NewAreaReportPanelLayout.setVerticalGroup(
            NewAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewAreaReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(NewAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NewAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TotalareamemberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Totaltargetmembership, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NewAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(NewAreaReportPanelLayout.createSequentialGroup()
                            .addComponent(PreviousMVPTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46)
                            .addComponent(JoindWorkTF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(dcaMatTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48)
                            .addComponent(VisitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(NewAreaReportPanelLayout.createSequentialGroup()
                            .addComponent(reportDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addGroup(NewAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TotalAreaCellTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CellattendTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NumberofHeldcellTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(newCellTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(45, 45, 45)
                            .addGroup(NewAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SundayAttendTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NewMVPTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(46, 46, 46)
                            .addGroup(NewAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(secondTimerTF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(OutreachTF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(44, 44, 44)
                            .addGroup(NewAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DcabasicTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EncTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(48, 48, 48)
                            .addGroup(NewAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DLITF, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CallsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(reportSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        AllareareportTable.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        AllareareportTable.setForeground(new java.awt.Color(51, 51, 51));
        AllareareportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Target", "Members", "Total Cells", "Cell Held", "new_cell", "Cell Attend", "Sunday Attend", "Previous MVPs", "New Mvps", "2nd Timers", "Workforce", "Outreach", "Basic", "Maturity", "Encounter", "DLI", "Visits", "Calls"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(AllareareportTable);

        javax.swing.GroupLayout AllAreaReportPanelLayout = new javax.swing.GroupLayout(AllAreaReportPanel);
        AllAreaReportPanel.setLayout(AllAreaReportPanelLayout);
        AllAreaReportPanelLayout.setHorizontalGroup(
            AllAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE)
        );
        AllAreaReportPanelLayout.setVerticalGroup(
            AllAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllAreaReportPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 201, Short.MAX_VALUE))
        );

        EditreportSearchSaveButton.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        EditreportSearchSaveButton.setText("SEARCH");
        EditreportSearchSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditreportSearchSaveButtonActionPerformed(evt);
            }
        });

        editreportlabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        editreportlabel.setText("ENTER THE REPORT DATE");

        EditareareportTable.setBackground(new java.awt.Color(51, 51, 51));
        EditareareportTable.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        EditareareportTable.setForeground(new java.awt.Color(255, 255, 255));
        EditareareportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Target", "Members", "Total Cells", "Cell Held", "new_cell", "Cell Attend", "Sunday Attend", "Previous MVPs", "New Mvps", "2nd Timers", "Workforce", "Outreach", "Basic", "Maturity", "Encounter", "DLI", "Visits", "Calls"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(EditareareportTable);

        javax.swing.GroupLayout EditAreaReportPanelLayout = new javax.swing.GroupLayout(EditAreaReportPanel);
        EditAreaReportPanel.setLayout(EditAreaReportPanelLayout);
        EditAreaReportPanelLayout.setHorizontalGroup(
            EditAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9)
            .addGroup(EditAreaReportPanelLayout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addGroup(EditAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editreportlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditreportDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditAreaReportPanelLayout.createSequentialGroup()
                        .addComponent(EditreportSearchSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)))
                .addContainerGap(735, Short.MAX_VALUE))
        );
        EditAreaReportPanelLayout.setVerticalGroup(
            EditAreaReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditAreaReportPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(EditreportDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editreportlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditreportSearchSaveButton)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1294, Short.MAX_VALUE)
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NewAreaReportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AllAreaReportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EditAreaReportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NewAreaReportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AllAreaReportPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EditAreaReportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AreaReportHomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreaReportHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void areareportBackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areareportBackbuttonActionPerformed
        // TODO add your handling code here:
        front.updatePanel(home);
    }//GEN-LAST:event_areareportBackbuttonActionPerformed

    private void NewReportLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewReportLabelMouseClicked
        // TODO add your handling code here:
         NewupdatePanel(NewAreaReportPanel);
         NewAreaReportPanel.setVisible(true);
    }//GEN-LAST:event_NewReportLabelMouseClicked

    private void ViewReportLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewReportLabelMouseClicked
        // TODO add your handling code here:
         NewupdatePanel(EditAreaReportPanel);
         EditAreaReportPanel.setVisible(true);
    }//GEN-LAST:event_ViewReportLabelMouseClicked

    private void AllReportLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllReportLabelMouseClicked
        // TODO add your handling code here:
             NewupdatePanel(AllAreaReportPanel);
             AllAreaReportPanel.setVisible(true);
             HashMap<String, String[]> objMap = db.getallareareport();
             TabularRecordUpdater upr = new TabularRecordUpdater (objMap,this);
             upr.populateallareaReportTable(objMap);       
    }//GEN-LAST:event_AllReportLabelMouseClicked

    private void reportSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportSaveButtonActionPerformed
        // TODO add your handling code here:
             SimpleDateFormat sFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date reports = reportDateChooser.getDate();
        
        String datereport = sFormat.format(reports);
        String Target =  Totaltargetmembership.getText();
        String Tmem = TotalareamemberTF.getText();
        String TCell  = TotalAreaCellTF.getText();
        String Pmvp    = PreviousMVPTF.getText();
        String Cellattend = CellattendTF.getText();
        String SundayAttend = SundayAttendTF.getText();
        String NewCell = newCellTF.getText();
        String NMvp = NewMVPTF.getText();
        String Cheld = NumberofHeldcellTF.getText();
        String Outreach = OutreachTF.getText();
        String Dcabasic = DcabasicTF.getText();
        String dcaMat = dcaMatTF.getText();
        String Enc = EncTF.getText();
        String DLI = DLITF.getText();
        String Visit = VisitTF.getText();
        String work = JoindWorkTF.getText();
        String SecTimer = secondTimerTF.getText();
        String calls = CallsTF.getText();
if(!validated(datereport,Target,Tmem,TCell,Pmvp,Cellattend,SundayAttend,NewCell,NMvp,Cheld,
            Outreach,Dcabasic,dcaMat,Enc,DLI,Visit,work,SecTimer,calls)){JOptionPane.showMessageDialog(this, "Please Fill in all Compulsory Spaces");}
  db.NewAreaReportSave(datereport,Target,Tmem,TCell,Pmvp,calls,Cellattend,SundayAttend,NewCell,NMvp,Cheld,Outreach,Dcabasic,dcaMat,Enc,DLI,Visit,work,SecTimer);
    
          }
private boolean validated(String datereport, String Target, String Tmem, String TCell, String Pmvp, String Cellattend, 
        String SundayAttend, String NewCell, String NMvp, String Cheld, String Outreach, String Dcabasic, String dcaMat, String Enc, 
        String DLI, String Visit, String work, String SecTimer, String calls) {
       
         if(datereport.isEmpty()|| Target.isEmpty()||Tmem.isEmpty()||TCell.isEmpty()||Pmvp.isEmpty()||Cellattend.isEmpty()||
           SundayAttend.isEmpty()||NewCell.isEmpty()||NMvp.isEmpty()||Cheld.isEmpty()||Outreach.isEmpty()||Dcabasic.isEmpty()||
           dcaMat.isEmpty()||Enc.isEmpty()||DLI.isEmpty()||Visit.isEmpty()||work.isEmpty()||SecTimer.isEmpty()||calls.isEmpty())
        {
            return false;
        }
         return true;
    }//GEN-LAST:event_reportSaveButtonActionPerformed

    private void EditreportSearchSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditreportSearchSaveButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date reports = EditreportDateChooser.getDate();
        String report = sFormat.format(reports);
        HashMap<String, String[]> objMap = db.getoneareareport(report);
        TabularRecordUpdater rup = new TabularRecordUpdater(objMap,this);
        rup.populateoneareaReportTable(objMap);
    }//GEN-LAST:event_EditreportSearchSaveButtonActionPerformed

    private void NewReportLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewReportLabelMouseEntered
        // TODO add your handling code here:
            Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
            Object obj = evt.getSource();
            JLabel lb = (JLabel) obj;
            lb.setCursor(handCursor);
    }//GEN-LAST:event_NewReportLabelMouseEntered

    public JTable getAllareareportTable() {
        return AllareareportTable;
    }

    public JTable getEditareareportTable() {
        return EditareareportTable;
    }

public void NewupdatePanel (JPanel currentPanel)
    {
        BackgroundPanel.removeAll();   
        GroupLayout l = (GroupLayout) BackgroundPanel.getLayout();   
        l.setHorizontalGroup(
            l.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        l.setVerticalGroup(
            l.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AllAreaReportPanel;
    private javax.swing.JLabel AllReportLabel;
    private javax.swing.JTable AllareareportTable;
    private javax.swing.JPanel AreaReportHomePanel;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JTextField CallsTF;
    private javax.swing.JTextField CellattendTF;
    private javax.swing.JTextField DLITF;
    private javax.swing.JTextField DcabasicTF;
    private javax.swing.JPanel EditAreaReportPanel;
    private javax.swing.JTable EditareareportTable;
    private com.toedter.calendar.JDateChooser EditreportDateChooser;
    private javax.swing.JButton EditreportSearchSaveButton;
    private javax.swing.JTextField EncTF;
    private javax.swing.JTextField JoindWorkTF;
    private javax.swing.JPanel NewAreaReportPanel;
    private javax.swing.JTextField NewMVPTF;
    private javax.swing.JLabel NewReportLabel;
    private javax.swing.JTextField NumberofHeldcellTF;
    private javax.swing.JTextField OutreachTF;
    private javax.swing.JTextField PreviousMVPTF;
    private javax.swing.JTextField SundayAttendTF;
    private javax.swing.JTextField TotalAreaCellTF;
    private javax.swing.JTextField TotalareamemberTF;
    private javax.swing.JTextField Totaltargetmembership;
    private javax.swing.JLabel ViewReportLabel;
    private javax.swing.JTextField VisitTF;
    private javax.swing.JButton areareportBackbutton;
    private javax.swing.JTextField dcaMatTF;
    private javax.swing.JLabel editreportlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField newCellTF;
    private com.toedter.calendar.JDateChooser reportDateChooser;
    private javax.swing.JButton reportSaveButton;
    private javax.swing.JTextField secondTimerTF;
    // End of variables declaration//GEN-END:variables
}
