/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.OkotaArea;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author chinex
 */
public class Cell extends javax.swing.JPanel {

    /**
     * Creates new form Cell
     */
 private final HomeFront front; 
 private final HomePanel  home; 
 DBOperations db = new DBOperations();
    public Cell(HomeFront front, HomePanel  home) {
        initComponents();
        this.front = front;
        this.home = home;
        NewCellReportPanel.setVisible(false);
        CellMemberPanel.setVisible(false);
        AllcellReportPanel.setVisible(false);
        ViewcellReportPanel.setVisible(false);
        textCustomise("Enter Total Target", CellTarget);
        textCustomise("Enter Total Population", CellPopulation);
        textCustomise("Enter Cell Start Time", CellStarttimeTF);
        textCustomise("Enter Cell End Time", CellEndtimeTF);
        textCustomise("Enter Number Attended Cell", CellattendTF);
        textCustomise("Total Attended Church Service", SundayAttendTF);
        textCustomise("Enter Name Of Cell Leader", NameOfCellLeader);
        textCustomise("Total Cell MVPs", CellMvpTf);
        textCustomise("Enter Number of 2nd Timers", ChurchsecondtimerTF);
        textCustomise("Total Church Mvps", ChurchMVPTF);
        textCustomise("Total Cell Offering",CellOfferingTf );
        textCustomise("Total Attended DCA Basic", DcabasicTF);
        textCustomise("Total Attended DCA Maturity", dcaMatTF);
        textCustomise("Total Attended Encounter", EncTF);
        textCustomise("Total Attended DLI", DLITF);
        textCustomise("Enter Number Of Visits", VisitTF);
        textCustomise("Enter Name Of Cell", NameOfCell);
    }
private void textCustomise(String text, JTextField component)
    {
        PromptSupport.setPrompt(text, component);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.HIDE_PROMPT, component);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, component);
        PromptSupport.setFontStyle(Font.BOLD, component);
        PromptSupport.setForeground(Color.darkGray, component);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CellHomePanel = new javax.swing.JPanel();
        cellBackbutton = new javax.swing.JButton();
        NewCellReportLabel = new javax.swing.JLabel();
        ViewCellReportLabel = new javax.swing.JLabel();
        AllCellReportLabel = new javax.swing.JLabel();
        AllCellMemberLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        BackgroundPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NewCellReportPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cellreportDateChooser = new com.toedter.calendar.JDateChooser();
        NameOfCell = new javax.swing.JTextField();
        NameOfCellLeader = new javax.swing.JTextField();
        CellattendTF = new javax.swing.JTextField();
        CellPopulation = new javax.swing.JTextField();
        CellTarget = new javax.swing.JTextField();
        SundayAttendTF = new javax.swing.JTextField();
        CellStarttimeTF = new javax.swing.JTextField();
        CellEndtimeTF = new javax.swing.JTextField();
        ChurchsecondtimerTF = new javax.swing.JTextField();
        CellMvpTf = new javax.swing.JTextField();
        ChurchMVPTF = new javax.swing.JTextField();
        DcabasicTF = new javax.swing.JTextField();
        dcaMatTF = new javax.swing.JTextField();
        EncTF = new javax.swing.JTextField();
        CellOfferingTf = new javax.swing.JTextField();
        VisitTF = new javax.swing.JTextField();
        cellreportSaveButton = new javax.swing.JButton();
        DLITF = new javax.swing.JTextField();
        ViewcellReportPanel = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        viewlcellreportTable = new javax.swing.JTable();
        EditreportDateChooser = new com.toedter.calendar.JDateChooser();
        editreportlabel = new javax.swing.JLabel();
        EditreportSearchButton = new javax.swing.JButton();
        EditreportSaveSaveButton = new javax.swing.JButton();
        AllcellReportPanel = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        allcellreportTable = new javax.swing.JTable();
        CellMemberPanel = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        AllcellmemberTable = new javax.swing.JTable();
        editreportlabel1 = new javax.swing.JLabel();
        cellmembersSearchButton = new javax.swing.JButton();
        cellMemberssearchTF = new javax.swing.JTextField();

        setBackground(new java.awt.Color(146, 198, 227));

        cellBackbutton.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        cellBackbutton.setText("BACK");
        cellBackbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellBackbuttonActionPerformed(evt);
            }
        });

        NewCellReportLabel.setBackground(new java.awt.Color(51, 51, 51));
        NewCellReportLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        NewCellReportLabel.setForeground(new java.awt.Color(51, 51, 51));
        NewCellReportLabel.setText("New Report");
        NewCellReportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewCellReportLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewCellReportLabelMouseEntered(evt);
            }
        });

        ViewCellReportLabel.setBackground(new java.awt.Color(51, 51, 51));
        ViewCellReportLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        ViewCellReportLabel.setForeground(new java.awt.Color(51, 51, 51));
        ViewCellReportLabel.setText("View Report");
        ViewCellReportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewCellReportLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewCellReportLabelMouseEntered(evt);
            }
        });

        AllCellReportLabel.setBackground(new java.awt.Color(51, 51, 51));
        AllCellReportLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        AllCellReportLabel.setForeground(new java.awt.Color(51, 51, 51));
        AllCellReportLabel.setText("All Cell Report");
        AllCellReportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllCellReportLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewCellReportLabelMouseEntered(evt);
            }
        });

        AllCellMemberLabel.setBackground(new java.awt.Color(51, 51, 51));
        AllCellMemberLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        AllCellMemberLabel.setForeground(new java.awt.Color(51, 51, 51));
        AllCellMemberLabel.setText("Cell Members ");
        AllCellMemberLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllCellMemberLabelMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/OkotaArea/logo smallsma.png"))); // NOI18N
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout CellHomePanelLayout = new javax.swing.GroupLayout(CellHomePanel);
        CellHomePanel.setLayout(CellHomePanelLayout);
        CellHomePanelLayout.setHorizontalGroup(
            CellHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AllCellReportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jSeparator4)
            .addComponent(jSeparator5)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CellHomePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CellHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CellHomePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CellHomePanelLayout.createSequentialGroup()
                        .addComponent(cellBackbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
            .addComponent(AllCellMemberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ViewCellReportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NewCellReportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CellHomePanelLayout.setVerticalGroup(
            CellHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CellHomePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewCellReportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ViewCellReportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(AllCellReportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AllCellMemberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(cellBackbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        BackgroundPanel.setBackground(new java.awt.Color(146, 198, 227));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/OkotaArea/DC Wallpaper101.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ENTER REPORT DETAILS");

        NameOfCell.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        NameOfCellLeader.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        CellattendTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        CellPopulation.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        CellTarget.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        SundayAttendTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        CellStarttimeTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        CellEndtimeTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        ChurchsecondtimerTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        CellMvpTf.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        ChurchMVPTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        DcabasicTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        dcaMatTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        EncTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        CellOfferingTf.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        VisitTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        cellreportSaveButton.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        cellreportSaveButton.setText("SAVE");
        cellreportSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellreportSaveButtonActionPerformed(evt);
            }
        });

        DLITF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        javax.swing.GroupLayout NewCellReportPanelLayout = new javax.swing.GroupLayout(NewCellReportPanel);
        NewCellReportPanel.setLayout(NewCellReportPanelLayout);
        NewCellReportPanelLayout.setHorizontalGroup(
            NewCellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewCellReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewCellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewCellReportPanelLayout.createSequentialGroup()
                        .addGroup(NewCellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cellreportDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChurchMVPTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SundayAttendTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CellTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DcabasicTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DLITF, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(NewCellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NameOfCell, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VisitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CellPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CellStarttimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CellMvpTf, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcaMatTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(NewCellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameOfCellLeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CellOfferingTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CellattendTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CellEndtimeTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChurchsecondtimerTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EncTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewCellReportPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewCellReportPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cellreportSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(434, 434, 434))
        );
        NewCellReportPanelLayout.setVerticalGroup(
            NewCellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewCellReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(NewCellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NewCellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NameOfCellLeader, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NameOfCell, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NewCellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(NewCellReportPanelLayout.createSequentialGroup()
                            .addComponent(CellPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45)
                            .addComponent(CellStarttimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46)
                            .addComponent(CellMvpTf, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(dcaMatTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48)
                            .addComponent(VisitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(NewCellReportPanelLayout.createSequentialGroup()
                            .addComponent(cellreportDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addGroup(NewCellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CellTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CellattendTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(45, 45, 45)
                            .addGroup(NewCellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SundayAttendTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CellEndtimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(46, 46, 46)
                            .addGroup(NewCellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ChurchMVPTF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ChurchsecondtimerTF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(44, 44, 44)
                            .addGroup(NewCellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DcabasicTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EncTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(48, 48, 48)
                            .addGroup(NewCellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DLITF, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CellOfferingTf, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cellreportSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        viewlcellreportTable.setBackground(new java.awt.Color(51, 51, 51));
        viewlcellreportTable.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        viewlcellreportTable.setForeground(new java.awt.Color(255, 255, 255));
        viewlcellreportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Cell Name", "Cell Leader", "Target", "Cell Population", "Start Time", "End Time", "Church attendance", "Cell Attendance", "Church Mvps", "Cell Mvps", "2nd Timers", "Offering", "Basic", "Maturity", "Encounter", "DLI", "Visits"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane12.setViewportView(viewlcellreportTable);

        editreportlabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        editreportlabel.setText("ENTER THE REPORT DATE");

        EditreportSearchButton.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        EditreportSearchButton.setText("SEARCH");
        EditreportSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditreportSearchButtonActionPerformed(evt);
            }
        });

        EditreportSaveSaveButton.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        EditreportSaveSaveButton.setText("SAVE");

        javax.swing.GroupLayout ViewcellReportPanelLayout = new javax.swing.GroupLayout(ViewcellReportPanel);
        ViewcellReportPanel.setLayout(ViewcellReportPanelLayout);
        ViewcellReportPanelLayout.setHorizontalGroup(
            ViewcellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewcellReportPanelLayout.createSequentialGroup()
                .addGroup(ViewcellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewcellReportPanelLayout.createSequentialGroup()
                        .addGroup(ViewcellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewcellReportPanelLayout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addGroup(ViewcellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editreportlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditreportDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewcellReportPanelLayout.createSequentialGroup()
                                        .addComponent(EditreportSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60))))
                            .addGroup(ViewcellReportPanelLayout.createSequentialGroup()
                                .addGap(296, 296, 296)
                                .addComponent(EditreportSaveSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 705, Short.MAX_VALUE))
                    .addComponent(jScrollPane12))
                .addContainerGap())
        );
        ViewcellReportPanelLayout.setVerticalGroup(
            ViewcellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewcellReportPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(EditreportDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editreportlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditreportSearchButton)
                .addGap(69, 69, 69)
                .addComponent(EditreportSaveSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        allcellreportTable.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        allcellreportTable.setForeground(new java.awt.Color(51, 51, 51));
        allcellreportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Cell Name", "Cell Leader", "Target", "Cell Population", "Start Time", "End Time", "Church attendance", "Cell Attendance", "Church Mvps", "Cell Mvps", "2nd Timers", "Offering", "Basic", "Maturity", "Encounter", "DLI", "Visits"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(allcellreportTable);

        javax.swing.GroupLayout AllcellReportPanelLayout = new javax.swing.GroupLayout(AllcellReportPanel);
        AllcellReportPanel.setLayout(AllcellReportPanelLayout);
        AllcellReportPanelLayout.setHorizontalGroup(
            AllcellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllcellReportPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 177, Short.MAX_VALUE))
        );
        AllcellReportPanelLayout.setVerticalGroup(
            AllcellReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllcellReportPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 300, Short.MAX_VALUE))
        );

        AllcellmemberTable.setBackground(new java.awt.Color(51, 51, 51));
        AllcellmemberTable.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        AllcellmemberTable.setForeground(new java.awt.Color(255, 255, 255));
        AllcellmemberTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Phone No", "Email", "Address", "Cell Jurisdiction", "Gender", "Marital Status", "Birthday", "Mvp date", "2nd Time", "DCA Basic", "Maturity", "Encounter", "DLI", "Department"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(AllcellmemberTable);

        editreportlabel1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        editreportlabel1.setText("ENTER THE CELL NAME");

        cellmembersSearchButton.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        cellmembersSearchButton.setText("SEARCH");
        cellmembersSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellmembersSearchButtonActionPerformed(evt);
            }
        });

        cellMemberssearchTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        javax.swing.GroupLayout CellMemberPanelLayout = new javax.swing.GroupLayout(CellMemberPanel);
        CellMemberPanel.setLayout(CellMemberPanelLayout);
        CellMemberPanelLayout.setHorizontalGroup(
            CellMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CellMemberPanelLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addGroup(CellMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cellMemberssearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CellMemberPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(editreportlabel1))
                    .addGroup(CellMemberPanelLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(cellmembersSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CellMemberPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CellMemberPanelLayout.setVerticalGroup(
            CellMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CellMemberPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(cellMemberssearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editreportlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(cellmembersSearchButton)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE)
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NewCellReportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ViewcellReportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AllcellReportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CellMemberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NewCellReportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ViewcellReportPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AllcellReportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CellMemberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CellHomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CellHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cellBackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellBackbuttonActionPerformed
        // TODO add your handling code here:
             front.updatePanel(home);
    }//GEN-LAST:event_cellBackbuttonActionPerformed

    private void NewCellReportLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewCellReportLabelMouseClicked
        // TODO add your handling code here:
             NewCellReportPanel.setVisible(true); 
             NewupdatePanel(NewCellReportPanel); 
    }//GEN-LAST:event_NewCellReportLabelMouseClicked

    private void ViewCellReportLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewCellReportLabelMouseClicked
        // TODO add your handling code here:
             ViewcellReportPanel.setVisible(true); 
             NewupdatePanel(ViewcellReportPanel); 
    }//GEN-LAST:event_ViewCellReportLabelMouseClicked

    private void AllCellReportLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllCellReportLabelMouseClicked
        // TODO add your handling code here:
             AllcellReportPanel.setVisible(true); 
             NewupdatePanel(AllcellReportPanel); 
             HashMap<String, String[]> objMap = db.getallCellreport();
             TabularRecordUpdater up = new TabularRecordUpdater(objMap,this);
             up.populateallCellReportTable(objMap);
    }//GEN-LAST:event_AllCellReportLabelMouseClicked

    private void AllCellMemberLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllCellMemberLabelMouseClicked
        // TODO add your handling code here:   
             CellMemberPanel.setVisible(true); 
             NewupdatePanel (CellMemberPanel);            
    }//GEN-LAST:event_AllCellMemberLabelMouseClicked

    private void cellmembersSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellmembersSearchButtonActionPerformed
        // TODO add your handling code here:
            HashMap<String, String[]> objMap = db.getCellMemberList(cellMemberssearchTF.getText());
            TabularRecordUpdater up = new TabularRecordUpdater(objMap,this);
            up.populateallCellMemberTable(objMap);
    }//GEN-LAST:event_cellmembersSearchButtonActionPerformed

    private void EditreportSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditreportSearchButtonActionPerformed
        // TODO add your handling code here:
            SimpleDateFormat sFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date reports = EditreportDateChooser.getDate();
            String report = sFormat.format(reports);
            HashMap<String, String[]> objMap = db.getoneCellreport(report);
            TabularRecordUpdater up = new TabularRecordUpdater(objMap,this);
            up.populateoneCellReportTable(objMap);
    }//GEN-LAST:event_EditreportSearchButtonActionPerformed

    private void cellreportSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellreportSaveButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date reports = cellreportDateChooser.getDate();
        
        String datereport = sFormat.format(reports);
        String CeTarget =  CellTarget.getText();
        String CePopulation = CellPopulation.getText();
        String CellStart  = CellStarttimeTF.getText();
        String CellEnd    = CellEndtimeTF.getText();
        String Cellattend = CellattendTF.getText();
        String SundayAttend = SundayAttendTF.getText();
        String CellLeader = NameOfCellLeader.getText();
        String CellMvp = CellMvpTf.getText();
        String ChurchMVP = ChurchMVPTF.getText();
        String CellOffering = CellOfferingTf.getText();
        String Dcabasic = DcabasicTF.getText();
        String dcaMat = dcaMatTF.getText();
        String Enc = EncTF.getText();
        String DLI = DLITF.getText();
        String Visit = VisitTF.getText();
        String CellName = NameOfCell.getText();
        String SecTimer = ChurchsecondtimerTF.getText();
if(!validated(datereport,CeTarget,CePopulation,CellStart,CellEnd,Cellattend,SundayAttend,CellLeader,CellMvp,ChurchMVP,
            CellOffering,Dcabasic,dcaMat,Enc,DLI,Visit,CellName,SecTimer)){JOptionPane.showMessageDialog(this, "Please Fill in all Compulsory Spaces");}
  db.NewCellReportSave(datereport,CeTarget,CePopulation,CellStart,CellEnd,Cellattend,SundayAttend,CellLeader,CellMvp,ChurchMVP,
                             CellOffering,Dcabasic,dcaMat,Enc,DLI,Visit,CellName,SecTimer);  

    }//GEN-LAST:event_cellreportSaveButtonActionPerformed

    private void NewCellReportLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewCellReportLabelMouseEntered
        // TODO add your handling code here:
            Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
            Object obj = evt.getSource();
            JLabel lb = (JLabel) obj;
            lb.setCursor(handCursor);
    }//GEN-LAST:event_NewCellReportLabelMouseEntered
 private boolean 
    validated(String datereport, String ceTarget, String phone, String addr, String mStatus, String cell,
              String gender, String dob, String CellMvp, String ChurchMVP, String CellOffering, String Dcabasic,
              String dcaMat, String Enc, String DLI, String Visit, String CellName, String SecTimer)
      {
      if(datereport.isEmpty()||ceTarget.isEmpty()||phone.isEmpty()||mStatus.isEmpty()||addr.isEmpty()||cell.isEmpty()||
           dob.isEmpty()||gender.isEmpty()||CellMvp.isEmpty()||ChurchMVP.isEmpty()||CellOffering.isEmpty()||Dcabasic.isEmpty()||
           dcaMat.isEmpty()||Enc.isEmpty()||DLI.isEmpty()||Visit.isEmpty()||CellName.isEmpty()||SecTimer.isEmpty())
        {
            return false;
        }
         return true;
      }
public JTable getAllareamemberTable() {
    return AllcellmemberTable;}
public JTable getAllcellreportTable() {
    return allcellreportTable;}
public JTable viewallcellreportTable(){
    return viewlcellreportTable;}

public void NewupdatePanel (JPanel currentPanel)
    {
        BackgroundPanel.removeAll();   
        GroupLayout l = (GroupLayout) BackgroundPanel.getLayout();   
        l.setHorizontalGroup(
            l.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        l.setVerticalGroup(
            l.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AllCellMemberLabel;
    private javax.swing.JLabel AllCellReportLabel;
    private javax.swing.JPanel AllcellReportPanel;
    private javax.swing.JTable AllcellmemberTable;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JTextField CellEndtimeTF;
    private javax.swing.JPanel CellHomePanel;
    private javax.swing.JPanel CellMemberPanel;
    private javax.swing.JTextField CellMvpTf;
    private javax.swing.JTextField CellOfferingTf;
    private javax.swing.JTextField CellPopulation;
    private javax.swing.JTextField CellStarttimeTF;
    private javax.swing.JTextField CellTarget;
    private javax.swing.JTextField CellattendTF;
    private javax.swing.JTextField ChurchMVPTF;
    private javax.swing.JTextField ChurchsecondtimerTF;
    private javax.swing.JTextField DLITF;
    private javax.swing.JTextField DcabasicTF;
    private com.toedter.calendar.JDateChooser EditreportDateChooser;
    private javax.swing.JButton EditreportSaveSaveButton;
    private javax.swing.JButton EditreportSearchButton;
    private javax.swing.JTextField EncTF;
    private javax.swing.JTextField NameOfCell;
    private javax.swing.JTextField NameOfCellLeader;
    private javax.swing.JLabel NewCellReportLabel;
    private javax.swing.JPanel NewCellReportPanel;
    private javax.swing.JTextField SundayAttendTF;
    private javax.swing.JLabel ViewCellReportLabel;
    private javax.swing.JPanel ViewcellReportPanel;
    private javax.swing.JTextField VisitTF;
    private javax.swing.JTable allcellreportTable;
    private javax.swing.JButton cellBackbutton;
    private javax.swing.JTextField cellMemberssearchTF;
    private javax.swing.JButton cellmembersSearchButton;
    private com.toedter.calendar.JDateChooser cellreportDateChooser;
    private javax.swing.JButton cellreportSaveButton;
    private javax.swing.JTextField dcaMatTF;
    private javax.swing.JLabel editreportlabel;
    private javax.swing.JLabel editreportlabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable viewlcellreportTable;
    // End of variables declaration//GEN-END:variables
}
