/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.OkotaArea;

import java.awt.Cursor;
import javax.swing.JLabel;

/**
 *
 * @author chinex
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
   
    private final HomeFront front; 
    public HomePanel(HomeFront front) {
        initComponents();
        this.front = front;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePanelback = new javax.swing.JPanel();
        cellLabel1 = new javax.swing.JLabel();
        ReportLabel1 = new javax.swing.JLabel();
        membershipLabel1 = new javax.swing.JLabel();
        dcaLabel1 = new javax.swing.JLabel();
        mvpLabel1 = new javax.swing.JLabel();
        newbelieverLabel1 = new javax.swing.JLabel();
        adminLabel1 = new javax.swing.JLabel();
        workerLabel1 = new javax.swing.JLabel();
        homepanelExitButton = new javax.swing.JButton();
        HomewelcomeLabel = new javax.swing.JLabel();

        setAutoscrolls(true);

        HomePanelback.setBackground(new java.awt.Color(102, 102, 102));
        HomePanelback.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(204, 204, 204)));
        HomePanelback.setPreferredSize(new java.awt.Dimension(990, 690));

        cellLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        cellLabel1.setForeground(new java.awt.Color(51, 51, 51));
        cellLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cellLabel1.setText("CELL");
        cellLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), null));
        cellLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cellLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                membershipLabel1MouseEntered(evt);
            }
        });

        ReportLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        ReportLabel1.setForeground(new java.awt.Color(51, 51, 51));
        ReportLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportLabel1.setText("AREA REPORT");
        ReportLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), null));
        ReportLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                membershipLabel1MouseEntered(evt);
            }
        });

        membershipLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        membershipLabel1.setForeground(new java.awt.Color(51, 51, 51));
        membershipLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        membershipLabel1.setText("MEMBERSHIP");
        membershipLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), null));
        membershipLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                membershipLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                membershipLabel1MouseEntered(evt);
            }
        });

        dcaLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        dcaLabel1.setForeground(new java.awt.Color(51, 51, 51));
        dcaLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dcaLabel1.setText("DISCIPLESHIP");
        dcaLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), null));
        dcaLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dcaLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                membershipLabel1MouseEntered(evt);
            }
        });

        mvpLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        mvpLabel1.setForeground(new java.awt.Color(51, 51, 51));
        mvpLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mvpLabel1.setText("MVP");
        mvpLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), null));
        mvpLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mvpLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                membershipLabel1MouseEntered(evt);
            }
        });

        newbelieverLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        newbelieverLabel1.setForeground(new java.awt.Color(51, 51, 51));
        newbelieverLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newbelieverLabel1.setText("NEW BELIVER");
        newbelieverLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), null));
        newbelieverLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newbelieverLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                membershipLabel1MouseEntered(evt);
            }
        });

        adminLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        adminLabel1.setForeground(new java.awt.Color(51, 51, 51));
        adminLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminLabel1.setText("ADMIN");
        adminLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), null));
        adminLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                membershipLabel1MouseEntered(evt);
            }
        });

        workerLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        workerLabel1.setForeground(new java.awt.Color(51, 51, 51));
        workerLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        workerLabel1.setText("WORKERS");
        workerLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), null));
        workerLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workerLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                membershipLabel1MouseEntered(evt);
            }
        });

        homepanelExitButton.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        homepanelExitButton.setText("EXIT");
        homepanelExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepanelExitButtonActionPerformed(evt);
            }
        });

        HomewelcomeLabel.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        HomewelcomeLabel.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout HomePanelbackLayout = new javax.swing.GroupLayout(HomePanelback);
        HomePanelback.setLayout(HomePanelbackLayout);
        HomePanelbackLayout.setHorizontalGroup(
            HomePanelbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, HomePanelbackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homepanelExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(HomewelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(HomePanelbackLayout.createSequentialGroup()
                .addGroup(HomePanelbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HomePanelbackLayout.createSequentialGroup()
                        .addComponent(membershipLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReportLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(HomePanelbackLayout.createSequentialGroup()
                        .addGroup(HomePanelbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mvpLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cellLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HomePanelbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newbelieverLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                            .addComponent(dcaLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HomePanelbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(workerLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adminLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        HomePanelbackLayout.setVerticalGroup(
            HomePanelbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelbackLayout.createSequentialGroup()
                .addGroup(HomePanelbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(homepanelExitButton)
                    .addComponent(HomewelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HomePanelbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(membershipLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(ReportLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(HomePanelbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(workerLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(dcaLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cellLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomePanelbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mvpLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(newbelieverLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(HomePanelback, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(HomePanelback, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("homeBackground");
    }// </editor-fold>//GEN-END:initComponents

    private void membershipLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membershipLabel1MouseClicked
        // TODO add your handling code here:
        Membership mem = new Membership(front, this);
        front.updatePanel(mem);
    }//GEN-LAST:event_membershipLabel1MouseClicked

    private void ReportLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportLabel1MouseClicked
        // TODO add your handling code here:
        AreaReport mem = new AreaReport(front, this);
        front.updatePanel(mem);
    }//GEN-LAST:event_ReportLabel1MouseClicked

    private void cellLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cellLabel1MouseClicked
        // TODO add your handling code here:
        Cell mem = new Cell(front, this);
        front.updatePanel(mem);
    }//GEN-LAST:event_cellLabel1MouseClicked

    private void dcaLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dcaLabel1MouseClicked
        // TODO add your handling code here:
        Discipleship mem = new Discipleship(front, this);
        front.updatePanel(mem);
    }//GEN-LAST:event_dcaLabel1MouseClicked

    private void workerLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workerLabel1MouseClicked
        // TODO add your handling code here:
        Workers mem = new Workers(front, this);
        front.updatePanel(mem);
    }//GEN-LAST:event_workerLabel1MouseClicked

    private void mvpLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mvpLabel1MouseClicked
        // TODO add your handling code here:
        MVP mem = new MVP(front, this);
        front.updatePanel(mem);
    }//GEN-LAST:event_mvpLabel1MouseClicked

    private void newbelieverLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newbelieverLabel1MouseClicked
        // TODO add your handling code here:
        NewBeliver mem = new NewBeliver(front, this);
        front.updatePanel(mem);
    }//GEN-LAST:event_newbelieverLabel1MouseClicked

    public JLabel getHomewelcomeLabel() {
        return HomewelcomeLabel;
    }
    private void adminLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLabel1MouseClicked
        // TODO add your handling code here:
        Admin mem = new Admin(front, this);
        front.updatePanel(mem);
    }//GEN-LAST:event_adminLabel1MouseClicked

    private void homepanelExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepanelExitButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> {
            new HomeFront().setVisible(true);
            front.dispose();
        });
    }//GEN-LAST:event_homepanelExitButtonActionPerformed

    private void membershipLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membershipLabel1MouseEntered
        // TODO add your handling code here:    
            Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
            Object obj = evt.getSource();
            JLabel lb = (JLabel) obj;
            lb.setCursor(handCursor);
    }//GEN-LAST:event_membershipLabel1MouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomePanelback;
    private javax.swing.JLabel HomewelcomeLabel;
    private javax.swing.JLabel ReportLabel1;
    private javax.swing.JLabel adminLabel1;
    private javax.swing.JLabel cellLabel1;
    private javax.swing.JLabel dcaLabel1;
    private javax.swing.JButton homepanelExitButton;
    private javax.swing.JLabel membershipLabel1;
    private javax.swing.JLabel mvpLabel1;
    private javax.swing.JLabel newbelieverLabel1;
    private javax.swing.JLabel workerLabel1;
    // End of variables declaration//GEN-END:variables
}
