/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.OkotaArea;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author chinex
 */
public class NewBeliver extends javax.swing.JPanel {

    /**
     * Creates new form NewBeliver
     */
 private final HomeFront front; 
 private final HomePanel  home; 
 DBOperations db = new DBOperations();
 SubPanelUpdater b = new SubPanelUpdater(this);
    public NewBeliver(HomeFront front, HomePanel  home) {
        initComponents();
        this.front = front;
        this.home = home;
        NewBeliverRegPanel.setVisible(false);
        ViewNewbeliverPanel.setVisible(false);
        AllNewbeliverPanel.setVisible(false);
        textCustomise("Enter First Name", nbFirstNameTf);
        textCustomise("Enter Last Name", nbLastNameTf);
        textCustomise("Enter Phone Number ", nbPhoneNumberTF);
        textCustomise("Enter Cell Jurisdiction", nbHomeCellJurisdiction1);
        textCustomise("Enter Address", nbAddress);
        textCustomise("Enter Email Address", nbemail);
        textCustomise("Enter New Believer's First Name", EnternewbelieverfnamesearchTF);
        textCustomise("Enter New Believer's Last Name", EnternewbeliverlnamesearchTF);
        textCustomise("Enter New Believer's Phone Number", EnternewbelivernumbersearchTF);
        
    }
private void textCustomise(String text, JTextField component)
    {
        PromptSupport.setPrompt(text, component);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.HIDE_PROMPT, component);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, component);
        PromptSupport.setFontStyle(Font.BOLD, component);
        PromptSupport.setForeground(Color.darkGray, component);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        NewBeliverHomePanel = new javax.swing.JPanel();
        newbelieverBackbutton = new javax.swing.JButton();
        EditNewbeliverLabel = new javax.swing.JLabel();
        NewbeliverLabel = new javax.swing.JLabel();
        AllNewbeliverLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        BackgroundPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NewBeliverRegPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nbFirstNameTf = new javax.swing.JTextField();
        nbLastNameTf = new javax.swing.JTextField();
        nbemail = new javax.swing.JTextField();
        nbPhoneNumberTF = new javax.swing.JTextField();
        nbAddress = new javax.swing.JTextField();
        nbmaleRadioButton = new javax.swing.JRadioButton();
        gender = new javax.swing.JLabel();
        nbfemaleRadioButton = new javax.swing.JRadioButton();
        gender1 = new javax.swing.JLabel();
        nbMarriedRadiobutton = new javax.swing.JRadioButton();
        nbSingleRadioButton = new javax.swing.JRadioButton();
        nbSalvarDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        NbSaveButton = new javax.swing.JButton();
        nbHomeCellJurisdiction1 = new javax.swing.JTextField();
        ViewNewbeliverPanel = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        ViewnewbeliverTable = new javax.swing.JTable();
        viewnewbelieverSaveButton = new javax.swing.JButton();
        SearchnewbeliverButton = new javax.swing.JButton();
        EnternewbelieverfnamesearchTF = new javax.swing.JTextField();
        EnternewbelivernumbersearchTF = new javax.swing.JTextField();
        entermemberNumberlabel2 = new javax.swing.JLabel();
        nberrorimagelabelnum = new javax.swing.JLabel();
        nberrorimagelabelfname = new javax.swing.JLabel();
        nberrorlabelfname = new javax.swing.JLabel();
        nberrorlabelnum = new javax.swing.JLabel();
        NBnumberRadioButton = new javax.swing.JRadioButton();
        NBfnameRadioButton = new javax.swing.JRadioButton();
        entermemberNumberlabel3 = new javax.swing.JLabel();
        EnternewbeliverlnamesearchTF = new javax.swing.JTextField();
        nberrorimagelabellname = new javax.swing.JLabel();
        nberrorlabellname = new javax.swing.JLabel();
        NBlnameRadioButton = new javax.swing.JRadioButton();
        AllNewbeliverPanel = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        AllnewbeliverTable = new javax.swing.JTable();
        sendmessageCombobox = new javax.swing.JComboBox();
        viewAllnewbeliversLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(146, 198, 227));

        newbelieverBackbutton.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        newbelieverBackbutton.setText("BACK");
        newbelieverBackbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbelieverBackbuttonActionPerformed(evt);
            }
        });

        EditNewbeliverLabel.setBackground(new java.awt.Color(51, 51, 51));
        EditNewbeliverLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        EditNewbeliverLabel.setForeground(new java.awt.Color(51, 51, 51));
        EditNewbeliverLabel.setText("View New Beliver");
        EditNewbeliverLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditNewbeliverLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewbeliverLabelMouseEntered(evt);
            }
        });

        NewbeliverLabel.setBackground(new java.awt.Color(51, 51, 51));
        NewbeliverLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        NewbeliverLabel.setForeground(new java.awt.Color(51, 51, 51));
        NewbeliverLabel.setText("New Beliver");
        NewbeliverLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewbeliverLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewbeliverLabelMouseEntered(evt);
            }
        });

        AllNewbeliverLabel.setBackground(new java.awt.Color(51, 51, 51));
        AllNewbeliverLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        AllNewbeliverLabel.setForeground(new java.awt.Color(51, 51, 51));
        AllNewbeliverLabel.setText("All New Beliver");
        AllNewbeliverLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllNewbeliverLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewbeliverLabelMouseEntered(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/OkotaArea/logo smallsma.png"))); // NOI18N
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout NewBeliverHomePanelLayout = new javax.swing.GroupLayout(NewBeliverHomePanel);
        NewBeliverHomePanel.setLayout(NewBeliverHomePanelLayout);
        NewBeliverHomePanelLayout.setHorizontalGroup(
            NewBeliverHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AllNewbeliverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(EditNewbeliverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
            .addComponent(NewbeliverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewBeliverHomePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NewBeliverHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewBeliverHomePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewBeliverHomePanelLayout.createSequentialGroup()
                        .addComponent(newbelieverBackbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        NewBeliverHomePanelLayout.setVerticalGroup(
            NewBeliverHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewBeliverHomePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewbeliverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditNewbeliverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AllNewbeliverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(newbelieverBackbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BackgroundPanel.setBackground(new java.awt.Color(146, 198, 227));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/OkotaArea/DC Wallpaper101.png"))); // NOI18N

        NewBeliverRegPanel.setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        nbFirstNameTf.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        nbLastNameTf.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        nbLastNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbLastNameTfActionPerformed(evt);
            }
        });

        nbemail.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        nbPhoneNumberTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        nbAddress.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        nbmaleRadioButton.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(nbmaleRadioButton);
        nbmaleRadioButton.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        nbmaleRadioButton.setForeground(new java.awt.Color(102, 102, 102));
        nbmaleRadioButton.setText("Male");

        gender.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        gender.setText("Gender");

        nbfemaleRadioButton.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(nbfemaleRadioButton);
        nbfemaleRadioButton.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        nbfemaleRadioButton.setForeground(new java.awt.Color(102, 102, 102));
        nbfemaleRadioButton.setText("Female");

        gender1.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        gender1.setText("Marital Status");

        nbMarriedRadiobutton.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup2.add(nbMarriedRadiobutton);
        nbMarriedRadiobutton.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        nbMarriedRadiobutton.setForeground(new java.awt.Color(102, 102, 102));
        nbMarriedRadiobutton.setText("Married");
        nbMarriedRadiobutton.setToolTipText("");

        nbSingleRadioButton.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup2.add(nbSingleRadioButton);
        nbSingleRadioButton.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        nbSingleRadioButton.setForeground(new java.awt.Color(102, 102, 102));
        nbSingleRadioButton.setText("Single");
        nbSingleRadioButton.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N
        jLabel6.setText("ENTER DATE OF DECISION");

        NbSaveButton.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        NbSaveButton.setText("SAVE");
        NbSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NbSaveButtonActionPerformed(evt);
            }
        });

        nbHomeCellJurisdiction1.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 584, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(NbSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(nbMarriedRadiobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(nbSingleRadioButton)
                                .addGap(36, 36, 36))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(nbAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nbLastNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nbemail, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nbHomeCellJurisdiction1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(gender)
                            .addGap(51, 51, 51)
                            .addComponent(nbmaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(nbfemaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(112, 112, 112)
                            .addComponent(gender1)
                            .addGap(0, 276, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(nbSalvarDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(459, 459, 459))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nbFirstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nbPhoneNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(nbLastNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(nbHomeCellJurisdiction1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nbAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nbemail, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nbMarriedRadiobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nbSingleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addComponent(NbSaveButton)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(nbFirstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)
                    .addComponent(nbPhoneNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(141, 141, 141)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nbmaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nbfemaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gender1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(nbSalvarDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(67, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout NewBeliverRegPanelLayout = new javax.swing.GroupLayout(NewBeliverRegPanel);
        NewBeliverRegPanel.setLayout(NewBeliverRegPanelLayout);
        NewBeliverRegPanelLayout.setHorizontalGroup(
            NewBeliverRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewBeliverRegPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        NewBeliverRegPanelLayout.setVerticalGroup(
            NewBeliverRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewBeliverRegPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        ViewnewbeliverTable.setBackground(new java.awt.Color(51, 51, 51));
        ViewnewbeliverTable.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        ViewnewbeliverTable.setForeground(new java.awt.Color(255, 255, 255));
        ViewnewbeliverTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Full Name", "Phone No", "Email", "Address", "Cell Jurisdiction", "Gender", "Marital Status", "Mvp date", "2nd Time", "Salvation Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(ViewnewbeliverTable);

        viewnewbelieverSaveButton.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        viewnewbelieverSaveButton.setText("SAVE");

        SearchnewbeliverButton.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        SearchnewbeliverButton.setText("SEARCH");
        SearchnewbeliverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchnewbeliverButtonActionPerformed(evt);
            }
        });

        EnternewbelieverfnamesearchTF.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        EnternewbelieverfnamesearchTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EnternewbelieverfnamesearchTFFocusLost(evt);
            }
        });

        EnternewbelivernumbersearchTF.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        EnternewbelivernumbersearchTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EnternewbelivernumbersearchTFFocusLost(evt);
            }
        });

        entermemberNumberlabel2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        entermemberNumberlabel2.setText("OR");

        nberrorimagelabelnum.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N

        nberrorimagelabelfname.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N

        nberrorlabelfname.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        nberrorlabelnum.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        buttonGroup3.add(NBnumberRadioButton);
        NBnumberRadioButton.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        NBnumberRadioButton.setText("Search With new believer's Phone Number");

        buttonGroup3.add(NBfnameRadioButton);
        NBfnameRadioButton.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        NBfnameRadioButton.setText("Search with New Believer's First Name");

        entermemberNumberlabel3.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        entermemberNumberlabel3.setText("OR");

        EnternewbeliverlnamesearchTF.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        EnternewbeliverlnamesearchTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EnternewbeliverlnamesearchTFFocusLost(evt);
            }
        });

        nberrorimagelabellname.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N

        nberrorlabellname.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        buttonGroup3.add(NBlnameRadioButton);
        NBlnameRadioButton.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        NBlnameRadioButton.setText("Search with New Believer's last Name");

        javax.swing.GroupLayout ViewNewbeliverPanelLayout = new javax.swing.GroupLayout(ViewNewbeliverPanel);
        ViewNewbeliverPanel.setLayout(ViewNewbeliverPanelLayout);
        ViewNewbeliverPanelLayout.setHorizontalGroup(
            ViewNewbeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8)
            .addGroup(ViewNewbeliverPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewNewbeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewNewbeliverPanelLayout.createSequentialGroup()
                        .addGroup(ViewNewbeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewNewbeliverPanelLayout.createSequentialGroup()
                                .addComponent(EnternewbelieverfnamesearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nberrorimagelabelfname, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nberrorlabelfname, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ViewNewbeliverPanelLayout.createSequentialGroup()
                                .addComponent(NBfnameRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entermemberNumberlabel2)))
                        .addGroup(ViewNewbeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewNewbeliverPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(ViewNewbeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ViewNewbeliverPanelLayout.createSequentialGroup()
                                        .addComponent(EnternewbelivernumbersearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nberrorimagelabelnum, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nberrorlabelnum, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ViewNewbeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ViewNewbeliverPanelLayout.createSequentialGroup()
                                        .addComponent(EnternewbeliverlnamesearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nberrorimagelabellname, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nberrorlabellname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(ViewNewbeliverPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(NBnumberRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(entermemberNumberlabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NBlnameRadioButton)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewNewbeliverPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SearchnewbeliverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(ViewNewbeliverPanelLayout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(viewnewbelieverSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ViewNewbeliverPanelLayout.setVerticalGroup(
            ViewNewbeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewNewbeliverPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewNewbeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NBfnameRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ViewNewbeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NBnumberRadioButton)
                        .addComponent(entermemberNumberlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NBlnameRadioButton)
                        .addComponent(entermemberNumberlabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(ViewNewbeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewNewbeliverPanelLayout.createSequentialGroup()
                        .addGroup(ViewNewbeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnternewbelivernumbersearchTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nberrorimagelabelnum, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nberrorimagelabelfname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnternewbelieverfnamesearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ViewNewbeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nberrorlabelnum, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nberrorlabelfname, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewNewbeliverPanelLayout.createSequentialGroup()
                        .addGroup(ViewNewbeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nberrorimagelabellname, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnternewbeliverlnamesearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nberrorlabellname, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(SearchnewbeliverButton)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(viewnewbelieverSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        AllnewbeliverTable.setBackground(new java.awt.Color(102, 102, 102));
        AllnewbeliverTable.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        AllnewbeliverTable.setForeground(new java.awt.Color(255, 255, 255));
        AllnewbeliverTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Phone No", "Email", "Address", "Cell Jurisdiction", "Gender", "Marital Status", "Mvp date", "2nd Time", "Salvation Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(AllnewbeliverTable);

        sendmessageCombobox.setBackground(new java.awt.Color(204, 204, 204));
        sendmessageCombobox.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        sendmessageCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Generate Contact Details", "Generate Email(s)", "Generate Phone Number(s)", "Generate Number with name", "Generate Email with name" }));
        sendmessageCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendmessageComboboxActionPerformed(evt);
            }
        });

        viewAllnewbeliversLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        viewAllnewbeliversLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout AllNewbeliverPanelLayout = new javax.swing.GroupLayout(AllNewbeliverPanel);
        AllNewbeliverPanel.setLayout(AllNewbeliverPanelLayout);
        AllNewbeliverPanelLayout.setHorizontalGroup(
            AllNewbeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AllNewbeliverPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AllNewbeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AllNewbeliverPanelLayout.createSequentialGroup()
                        .addComponent(sendmessageCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AllNewbeliverPanelLayout.createSequentialGroup()
                        .addComponent(viewAllnewbeliversLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))))
        );
        AllNewbeliverPanelLayout.setVerticalGroup(
            AllNewbeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllNewbeliverPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(viewAllnewbeliversLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sendmessageCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, Short.MAX_VALUE)
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NewBeliverRegPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ViewNewbeliverPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AllNewbeliverPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, Short.MAX_VALUE)
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NewBeliverRegPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ViewNewbeliverPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AllNewbeliverPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NewBeliverHomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NewBeliverHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newbelieverBackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbelieverBackbuttonActionPerformed
        // TODO add your handling code here:
        front.updatePanel(home);
    }//GEN-LAST:event_newbelieverBackbuttonActionPerformed

    private void NewbeliverLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewbeliverLabelMouseClicked
        // TODO add your handling code here:
          NewBeliverRegPanel.setVisible(true);
          NewupdatePanel(NewBeliverRegPanel);
    }//GEN-LAST:event_NewbeliverLabelMouseClicked

    private void EditNewbeliverLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditNewbeliverLabelMouseClicked
        // TODO add your handling code here:
          ViewNewbeliverPanel.setVisible(true);
          NewupdatePanel(ViewNewbeliverPanel);
    }//GEN-LAST:event_EditNewbeliverLabelMouseClicked

    private void AllNewbeliverLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllNewbeliverLabelMouseClicked
        // TODO add your handling code here:
          HashMap<String, String[]> objMap = db.getAllNewBelieverList();
          TabularRecordUpdater tb = new TabularRecordUpdater(objMap,this);
          AllNewbeliverPanel.setVisible(true);
          NewupdatePanel (AllNewbeliverPanel); 
          tb.populateallNBTable(objMap); 
          viewAllnewbeliversLabel.setText("All New Belivers");
    }//GEN-LAST:event_AllNewbeliverLabelMouseClicked

    private void NbSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NbSaveButtonActionPerformed
        // TODO add your handling code here:
         String mStatus,NBgender;
        if (nbmaleRadioButton.isSelected()){NBgender = "Male"; }
            else {NBgender = "Female";}
        if (nbSingleRadioButton.isSelected()){mStatus = "Single"; }
            else {mStatus = "Married"; }
       
        String firstname = nbFirstNameTf.getText();
        String lastname = nbLastNameTf.getText(); 
        String phone = nbPhoneNumberTF.getText();
        String addr = nbAddress.getText();
        String mail  = nbemail.getText();
        String cell = nbHomeCellJurisdiction1.getText();
        Date salvadat ,sec;
        SimpleDateFormat sFormat = new SimpleDateFormat("yyyy-MM-dd");
        salvadat = nbSalvarDateChooser.getDate();
        String salvadate = sFormat.format(salvadat);
        
        if(!validated(firstname,lastname, phone,mail, addr, mStatus, cell, NBgender,salvadate)){JOptionPane.showMessageDialog(this, "Please Fill in all Compulsory Spaces");}
            else{       
           db.NewBelieversave(firstname,lastname, phone,mail, addr, cell, NBgender, mStatus, salvadate); 
        nbAddress.setText("");
        nbFirstNameTf.setText("");
        nbLastNameTf.setText("");
        nbemail.setText("");
        nbPhoneNumberTF.setText("");
        nbSalvarDateChooser.setDate(null);
        nbHomeCellJurisdiction1.setText("");
        }  
    }//GEN-LAST:event_NbSaveButtonActionPerformed

    private void SearchnewbeliverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchnewbeliverButtonActionPerformed
        // TODO add your handling code here:
         if (NBfnameRadioButton.isSelected())
        {
                String name = EnternewbelieverfnamesearchTF.getText();
                HashMap<String, String[]> objMap =  db.getANewBelieverRecordfname(name);
                 if (objMap.isEmpty())
                {
                    nberrorlabelfname.setText("Please Enter the Correct Full Name");
                    nberrorimagelabelfname.setIcon(new javax.swing.ImageIcon("images/badsign.png"));
                }
                else
                 {
                   TabularRecordUpdater tbup = new TabularRecordUpdater(objMap,this);
                   tbup.populateOneNBTable(objMap); }
          }
        else if(NBnumberRadioButton.isSelected())
          {
                String num = EnternewbelivernumbersearchTF.getText();
                HashMap<String, String[]> objMap =  db.getANewBelieverRecordnum(num);
                 if (objMap.isEmpty())
                {
                    nberrorlabelnum.setText("Please Enter the Correct Phone Number");
                    nberrorimagelabelnum.setIcon(new javax.swing.ImageIcon("images/badsign.png"));
                }
                else{
                   TabularRecordUpdater tbup = new TabularRecordUpdater(objMap,this);
                   tbup.populateOneNBTable(objMap); }
            }
         if (NBlnameRadioButton.isSelected())
        {
                String name = EnternewbeliverlnamesearchTF.getText();
                HashMap<String, String[]> objMap =  db.getANewBelieverRecordlname(name);
                 if (objMap.isEmpty())
                {
                    nberrorlabellname.setText("Please Enter the Correct Full Name");
                    nberrorimagelabellname.setIcon(new javax.swing.ImageIcon("images/badsign.png"));
                }
                else
                 {
                   TabularRecordUpdater tbup = new TabularRecordUpdater(objMap,this);
                   tbup.populateOneNBTable(objMap); }
          }
    }//GEN-LAST:event_SearchnewbeliverButtonActionPerformed

    private void EnternewbelieverfnamesearchTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EnternewbelieverfnamesearchTFFocusLost
        // TODO add your handling code here:
            nberrorlabelfname.setText(" ");
            nberrorimagelabelfname.setIcon(null);
       
    }//GEN-LAST:event_EnternewbelieverfnamesearchTFFocusLost

    private void EnternewbelivernumbersearchTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EnternewbelivernumbersearchTFFocusLost
        // TODO add your handling code here:
             nberrorlabelnum.setText(" ");
             nberrorimagelabelnum.setIcon(null);
    }//GEN-LAST:event_EnternewbelivernumbersearchTFFocusLost

    private void EnternewbeliverlnamesearchTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EnternewbeliverlnamesearchTFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_EnternewbeliverlnamesearchTFFocusLost

    private void NewbeliverLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewbeliverLabelMouseEntered
        // TODO add your handling code here:
            Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
            Object obj = evt.getSource();
            JLabel lb = (JLabel) obj;
            lb.setCursor(handCursor);
    }//GEN-LAST:event_NewbeliverLabelMouseEntered

    private void nbLastNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbLastNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbLastNameTfActionPerformed

    private void sendmessageComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendmessageComboboxActionPerformed
        // TODO add your handling code here:
        String gen = (String)sendmessageCombobox.getSelectedItem();
        switch(gen)
        {

            case "Generate Email(s)":
            {
                b.getemails("Always delete File After Use before generating another Contact.");
                b.getemails("\t" + viewAllnewbeliversLabel.getText());
                int count = AllnewbeliverTable.getRowCount();
                for (int i=0; i<count; i++)
                {
                    String email = (String) AllnewbeliverTable.getValueAt(i,4);
                    b.getemails(email);
                }
                JOptionPane.showMessageDialog(front, "Generated Sucessfully");
                break;
            }
            case "Generate Phone Number(s)":
            {
                b.getNumber("Always delete File After Use before generating another Contact.");
                b.getNumber("\t" + viewAllnewbeliversLabel.getText());
                int count = AllnewbeliverTable.getRowCount();
                for (int i=0; i<count; i++)
                {
                    String ph = (String) AllnewbeliverTable.getValueAt(i,3);
                    b.getNumber(ph);
                }
                JOptionPane.showMessageDialog(front, "Generated Sucessfully");
                break;
            }
           case "Generate Number with name":
                {
                    b.getNumber("Always delete File After Use before generating another Contact List.");
                    b.getNumber("\t" + viewAllnewbeliversLabel.getText());
                    int count = AllnewbeliverTable.getRowCount();
                    for (int i=0; i<count; i++)
                    {
                        String ph = (String) AllnewbeliverTable.getValueAt(i,3);
                        String fn = (String) AllnewbeliverTable.getValueAt(i,1);
                        String ln = (String) AllnewbeliverTable.getValueAt(i,2);
                        b.getNumber(fn + "  " + ln + "\t" + "\t"  + ph);
                    }
                    JOptionPane.showMessageDialog(front, "Generated Sucessfully");
                    break;
                }
            case "Generate Email with name":
                {
                    b.getNumber("Always delete File After Use before generating another Contact List.");
                    b.getNumber("\t" + viewAllnewbeliversLabel.getText());
                    int count = AllnewbeliverTable.getRowCount();
                    for (int i=0; i<count; i++)
                    {
                        String email = (String) AllnewbeliverTable.getValueAt(i,4);
                        String fn = (String) AllnewbeliverTable.getValueAt(i,1);
                        String ln = (String) AllnewbeliverTable.getValueAt(i,2);
                        b.getemails(fn + "  " + ln + "\t" + "\t"  + email);
                    }
                    JOptionPane.showMessageDialog(front, "Generated Sucessfully");
                    break;
                }
            default:
        }
    }//GEN-LAST:event_sendmessageComboboxActionPerformed
private boolean 
    validated(String firstname,String lastname, String phone,String mail, String addr, String mStatus, String cell, String gender,String salvadate)
      {
        if(firstname.isEmpty()||lastname.isEmpty()||phone.isEmpty()||mail.isEmpty()||cell.isEmpty()||addr.isEmpty()||gender.isEmpty()||salvadate.isEmpty())
        {
            return false;
        }
         return true;
      }

public JTable getViewnewbeliverTable() {
    return ViewnewbeliverTable;
}

public JTable getAllnewbeliverTable() {
    return AllnewbeliverTable;
}

public void NewupdatePanel (JPanel currentPanel)
    {
        BackgroundPanel.removeAll();   
        GroupLayout l = (GroupLayout) BackgroundPanel.getLayout();   
        l.setHorizontalGroup(
            l.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        l.setVerticalGroup(
            l.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AllNewbeliverLabel;
    private javax.swing.JPanel AllNewbeliverPanel;
    private javax.swing.JTable AllnewbeliverTable;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel EditNewbeliverLabel;
    private javax.swing.JTextField EnternewbelieverfnamesearchTF;
    private javax.swing.JTextField EnternewbeliverlnamesearchTF;
    private javax.swing.JTextField EnternewbelivernumbersearchTF;
    private javax.swing.JRadioButton NBfnameRadioButton;
    private javax.swing.JRadioButton NBlnameRadioButton;
    private javax.swing.JRadioButton NBnumberRadioButton;
    private javax.swing.JButton NbSaveButton;
    private javax.swing.JPanel NewBeliverHomePanel;
    private javax.swing.JPanel NewBeliverRegPanel;
    private javax.swing.JLabel NewbeliverLabel;
    private javax.swing.JButton SearchnewbeliverButton;
    private javax.swing.JPanel ViewNewbeliverPanel;
    private javax.swing.JTable ViewnewbeliverTable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel entermemberNumberlabel2;
    private javax.swing.JLabel entermemberNumberlabel3;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel gender1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField nbAddress;
    private javax.swing.JTextField nbFirstNameTf;
    private javax.swing.JTextField nbHomeCellJurisdiction1;
    private javax.swing.JTextField nbLastNameTf;
    private javax.swing.JRadioButton nbMarriedRadiobutton;
    private javax.swing.JTextField nbPhoneNumberTF;
    private com.toedter.calendar.JDateChooser nbSalvarDateChooser;
    private javax.swing.JRadioButton nbSingleRadioButton;
    private javax.swing.JTextField nbemail;
    private javax.swing.JLabel nberrorimagelabelfname;
    private javax.swing.JLabel nberrorimagelabellname;
    private javax.swing.JLabel nberrorimagelabelnum;
    private javax.swing.JLabel nberrorlabelfname;
    private javax.swing.JLabel nberrorlabellname;
    private javax.swing.JLabel nberrorlabelnum;
    private javax.swing.JRadioButton nbfemaleRadioButton;
    private javax.swing.JRadioButton nbmaleRadioButton;
    private javax.swing.JButton newbelieverBackbutton;
    private javax.swing.JComboBox sendmessageCombobox;
    private javax.swing.JLabel viewAllnewbeliversLabel;
    private javax.swing.JButton viewnewbelieverSaveButton;
    // End of variables declaration//GEN-END:variables
}
