/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.OkotaArea;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.util.HashMap;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author chinex
 */
public class Workers extends javax.swing.JPanel {

    /**
     * Creates new form Workers
     */
    private final HomeFront front; 
    private final HomePanel  home;
    DBOperations db = new DBOperations();
    SubPanelUpdater w = new SubPanelUpdater(this);
    public Workers(HomeFront front, HomePanel  home) {
        initComponents();       
        this.front = front;
        this.home = home;
        NewWorkerRegPanel.setVisible(false);
        AllWorkersPanel.setVisible(false);
        ViewWorkersPanel.setVisible(false);
        textCustomise("Enter First Name", wkFirstNameTf);
        textCustomise("Enter Last Name", wkLastNameTF);
        textCustomise("Enter Phone Number ", wkPhoneNumberTF);
        textCustomise("Enter Cell Jurisdiction", wkHomeCellJurisdictionTF);
        textCustomise("Enter Worker's First Name", EnterworkfnamesearchTF);
        textCustomise("Enter Worker's Last Name", EnterworklnamesearchTF);
        
    }
private void textCustomise(String text, JTextField component)
    {
        PromptSupport.setPrompt(text, component);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.HIDE_PROMPT, component);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, component);
        PromptSupport.setFontStyle(Font.BOLD, component);
        PromptSupport.setForeground(Color.darkGray, component);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        WorkerHomepanel = new javax.swing.JPanel();
        NewWorkLabel = new javax.swing.JLabel();
        ViewWorkLabel = new javax.swing.JLabel();
        AllWorkLabel = new javax.swing.JLabel();
        workersBackbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        BackgroundPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NewWorkerRegPanel = new javax.swing.JPanel();
        NewWorkRegPanelIN = new javax.swing.JPanel();
        wkFirstNameTf = new javax.swing.JTextField();
        wkPhoneNumberTF = new javax.swing.JTextField();
        wkHomeCellJurisdictionTF = new javax.swing.JTextField();
        wkLastNameTF = new javax.swing.JTextField();
        newWorkerSaveButton = new javax.swing.JButton();
        deptregComboBox = new javax.swing.JComboBox();
        ViewWorkersPanel = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        ViewworkerTable = new javax.swing.JTable();
        EditworkerSaveButton = new javax.swing.JButton();
        SearchworkerButton = new javax.swing.JButton();
        workfnamesearchRadioButton = new javax.swing.JRadioButton();
        EnterworkfnamesearchTF = new javax.swing.JTextField();
        workfnameerrorlabel = new javax.swing.JLabel();
        workerrorimagefname = new javax.swing.JLabel();
        entermemberNumberlabel2 = new javax.swing.JLabel();
        worksearchnumberRadioButton = new javax.swing.JRadioButton();
        entermemberNumberlabel3 = new javax.swing.JLabel();
        worksearchlnameRadioButton = new javax.swing.JRadioButton();
        EnterworklnamesearchTF = new javax.swing.JTextField();
        worklnameerrorlabel = new javax.swing.JLabel();
        workerrorimagelnamelabel = new javax.swing.JLabel();
        deptsearchComboBox = new javax.swing.JComboBox();
        depterrorlabel = new javax.swing.JLabel();
        AllWorkersPanel = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        allworkersTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(146, 198, 227));
        setForeground(new java.awt.Color(51, 51, 51));

        NewWorkLabel.setBackground(new java.awt.Color(51, 51, 51));
        NewWorkLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        NewWorkLabel.setForeground(new java.awt.Color(51, 51, 51));
        NewWorkLabel.setText("New Worker");
        NewWorkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewWorkLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewWorkLabelMouseEntered(evt);
            }
        });

        ViewWorkLabel.setBackground(new java.awt.Color(51, 51, 51));
        ViewWorkLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        ViewWorkLabel.setForeground(new java.awt.Color(51, 51, 51));
        ViewWorkLabel.setText("View Workers");
        ViewWorkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewWorkLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewWorkLabelMouseEntered(evt);
            }
        });

        AllWorkLabel.setBackground(new java.awt.Color(51, 51, 51));
        AllWorkLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        AllWorkLabel.setForeground(new java.awt.Color(51, 51, 51));
        AllWorkLabel.setText("All Workers");
        AllWorkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllWorkLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewWorkLabelMouseEntered(evt);
            }
        });

        workersBackbutton.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        workersBackbutton.setText("BACK");
        workersBackbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workersBackbuttonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/OkotaArea/logo smallsma.png"))); // NOI18N
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout WorkerHomepanelLayout = new javax.swing.GroupLayout(WorkerHomepanel);
        WorkerHomepanel.setLayout(WorkerHomepanelLayout);
        WorkerHomepanelLayout.setHorizontalGroup(
            WorkerHomepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AllWorkLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ViewWorkLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
            .addComponent(NewWorkLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator4)
            .addComponent(jSeparator5)
            .addGroup(WorkerHomepanelLayout.createSequentialGroup()
                .addGroup(WorkerHomepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WorkerHomepanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WorkerHomepanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(workersBackbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        WorkerHomepanelLayout.setVerticalGroup(
            WorkerHomepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkerHomepanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewWorkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewWorkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AllWorkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(workersBackbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        BackgroundPanel.setBackground(new java.awt.Color(146, 198, 227));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/OkotaArea/DC Wallpaper101.png"))); // NOI18N

        NewWorkerRegPanel.setBackground(new java.awt.Color(102, 102, 102));

        NewWorkRegPanelIN.setBackground(new java.awt.Color(204, 204, 204));

        wkFirstNameTf.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        wkPhoneNumberTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        wkHomeCellJurisdictionTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        wkLastNameTF.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N

        newWorkerSaveButton.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        newWorkerSaveButton.setText("SAVE");
        newWorkerSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWorkerSaveButtonActionPerformed(evt);
            }
        });

        deptregComboBox.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        deptregComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administration", "Book Shop", "Children Church", "Choir", "Dominion City Academy Management", "Follow Up", "Info Desk", "Maintainance", "Media", "Outreach and Missions", "Prayer", "Santuary", "Sound and Equipments", "Teen Chuirch", "Ushering", "Welfare", " ", " ", " ", " " }));

        javax.swing.GroupLayout NewWorkRegPanelINLayout = new javax.swing.GroupLayout(NewWorkRegPanelIN);
        NewWorkRegPanelIN.setLayout(NewWorkRegPanelINLayout);
        NewWorkRegPanelINLayout.setHorizontalGroup(
            NewWorkRegPanelINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewWorkRegPanelINLayout.createSequentialGroup()
                .addGroup(NewWorkRegPanelINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewWorkRegPanelINLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(newWorkerSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NewWorkRegPanelINLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(NewWorkRegPanelINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wkFirstNameTf, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(wkPhoneNumberTF, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(NewWorkRegPanelINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(wkLastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wkHomeCellJurisdictionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewWorkRegPanelINLayout.createSequentialGroup()
                .addGap(0, 49, Short.MAX_VALUE)
                .addComponent(deptregComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        NewWorkRegPanelINLayout.setVerticalGroup(
            NewWorkRegPanelINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewWorkRegPanelINLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(NewWorkRegPanelINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NewWorkRegPanelINLayout.createSequentialGroup()
                        .addComponent(wkLastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(wkHomeCellJurisdictionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NewWorkRegPanelINLayout.createSequentialGroup()
                        .addComponent(wkFirstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(wkPhoneNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(deptregComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGap(61, 61, 61)
                .addComponent(newWorkerSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout NewWorkerRegPanelLayout = new javax.swing.GroupLayout(NewWorkerRegPanel);
        NewWorkerRegPanel.setLayout(NewWorkerRegPanelLayout);
        NewWorkerRegPanelLayout.setHorizontalGroup(
            NewWorkerRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewWorkerRegPanelLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(NewWorkRegPanelIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        NewWorkerRegPanelLayout.setVerticalGroup(
            NewWorkerRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewWorkerRegPanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(NewWorkRegPanelIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        ViewworkerTable.setBackground(new java.awt.Color(51, 51, 51));
        ViewworkerTable.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        ViewworkerTable.setForeground(new java.awt.Color(255, 255, 255));
        ViewworkerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Phone No", "Email", "Address", "Cell Jurisdiction", "Gender", "Marital Status", "Birthday", "Mvp date", "2nd Time", "Department"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(ViewworkerTable);

        EditworkerSaveButton.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        EditworkerSaveButton.setText("SAVE");

        SearchworkerButton.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        SearchworkerButton.setText("SEARCH");
        SearchworkerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchworkerButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(workfnamesearchRadioButton);
        workfnamesearchRadioButton.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        workfnamesearchRadioButton.setText("Search by Worker's First Name");

        EnterworkfnamesearchTF.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        EnterworkfnamesearchTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EnterworkfnamesearchTFFocusLost(evt);
            }
        });

        workfnameerrorlabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N

        workerrorimagefname.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N

        entermemberNumberlabel2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        entermemberNumberlabel2.setText("OR");

        buttonGroup1.add(worksearchnumberRadioButton);
        worksearchnumberRadioButton.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        worksearchnumberRadioButton.setText("Search by Department");
        worksearchnumberRadioButton.setActionCommand("Search with Worker's Phone Number");

        entermemberNumberlabel3.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        entermemberNumberlabel3.setText("OR");

        buttonGroup1.add(worksearchlnameRadioButton);
        worksearchlnameRadioButton.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        worksearchlnameRadioButton.setText("Search by Worker's Last Name");

        EnterworklnamesearchTF.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        EnterworklnamesearchTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EnterworklnamesearchTFFocusLost(evt);
            }
        });

        worklnameerrorlabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N

        workerrorimagelnamelabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N

        deptsearchComboBox.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        deptsearchComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administration", "Book Shop", "Children Church", "Choir", "Dominion City Academy Management", "Follow Up", "Info Desk", "Maintainance", "Media", "Outreach and Missions", "Prayer", "Santuary", "Sound and Equipments", "Teen Chuirch", "Ushering", "Welfare", " ", " " }));

        depterrorlabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N

        javax.swing.GroupLayout ViewWorkersPanelLayout = new javax.swing.GroupLayout(ViewWorkersPanel);
        ViewWorkersPanel.setLayout(ViewWorkersPanelLayout);
        ViewWorkersPanelLayout.setHorizontalGroup(
            ViewWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewWorkersPanelLayout.createSequentialGroup()
                .addGroup(ViewWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewWorkersPanelLayout.createSequentialGroup()
                        .addComponent(EnterworkfnamesearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(workerrorimagefname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deptsearchComboBox, 0, 1, Short.MAX_VALUE))
                    .addGroup(ViewWorkersPanelLayout.createSequentialGroup()
                        .addComponent(workfnamesearchRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(entermemberNumberlabel2)
                        .addGap(45, 45, 45)
                        .addComponent(worksearchnumberRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE))
                    .addGroup(ViewWorkersPanelLayout.createSequentialGroup()
                        .addComponent(workfnameerrorlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(depterrorlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(ViewWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(ViewWorkersPanelLayout.createSequentialGroup()
                        .addComponent(entermemberNumberlabel3)
                        .addGap(26, 26, 26)
                        .addComponent(worksearchlnameRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ViewWorkersPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(ViewWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(worklnameerrorlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ViewWorkersPanelLayout.createSequentialGroup()
                                .addComponent(EnterworklnamesearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(workerrorimagelnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))))
            .addGroup(ViewWorkersPanelLayout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(EditworkerSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewWorkersPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchworkerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        ViewWorkersPanelLayout.setVerticalGroup(
            ViewWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewWorkersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(workfnamesearchRadioButton)
                        .addComponent(worksearchnumberRadioButton)
                        .addComponent(entermemberNumberlabel3)
                        .addComponent(entermemberNumberlabel2))
                    .addComponent(worksearchlnameRadioButton))
                .addGap(33, 33, 33)
                .addGroup(ViewWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ViewWorkersPanelLayout.createSequentialGroup()
                        .addGroup(ViewWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(workerrorimagefname, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ViewWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(EnterworkfnamesearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deptsearchComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ViewWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(workfnameerrorlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                            .addComponent(depterrorlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(ViewWorkersPanelLayout.createSequentialGroup()
                        .addGroup(ViewWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnterworklnamesearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(workerrorimagelnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(worklnameerrorlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(SearchworkerButton)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(EditworkerSaveButton)
                .addGap(99, 99, 99))
        );

        allworkersTable.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        allworkersTable.setForeground(new java.awt.Color(51, 51, 51));
        allworkersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Phone No", "Email", "Address", "Cell Jurisdiction", "Gender", "Marital Status", "Birthday", "Mvp date", "2nd Time", "Department"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(allworkersTable);

        javax.swing.GroupLayout AllWorkersPanelLayout = new javax.swing.GroupLayout(AllWorkersPanel);
        AllWorkersPanel.setLayout(AllWorkersPanelLayout);
        AllWorkersPanelLayout.setHorizontalGroup(
            AllWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
        );
        AllWorkersPanelLayout.setVerticalGroup(
            AllWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllWorkersPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 343, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 974, Short.MAX_VALUE)
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NewWorkerRegPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ViewWorkersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AllWorkersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, Short.MAX_VALUE)
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(NewWorkerRegPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ViewWorkersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AllWorkersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(WorkerHomepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WorkerHomepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void workersBackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workersBackbuttonActionPerformed
        // TODO add your handling code here:
        front.updatePanel(home);
    }//GEN-LAST:event_workersBackbuttonActionPerformed

    private void NewWorkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewWorkLabelMouseClicked
        // TODO add your handling code here:       
//          SubPanelUpdater w = new SubPanelUpdater(this);
//           BackgroundPanel.removeAll();
//          w.NewupdatePanel(NewWorkerRegPanel);
//          BackgroundPanel.removeAll();
//          w.NewupdatePanel(NewWorkerRegPanel); 
//          NewWorkerRegPanel.setVisible(true);
          NewWorkerRegPanel.setVisible(true);
          NewupdatePanel(NewWorkerRegPanel);
          
    }//GEN-LAST:event_NewWorkLabelMouseClicked

    private void ViewWorkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewWorkLabelMouseClicked
        // TODO add your handling code here:
          ViewWorkersPanel.setVisible(true);
          NewupdatePanel(ViewWorkersPanel);
    }//GEN-LAST:event_ViewWorkLabelMouseClicked

    private void AllWorkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllWorkLabelMouseClicked
        // TODO add your handling code here:
           HashMap<String, String[]> objMap = db.getAllWorkersList();
           TabularRecordUpdater tw = new TabularRecordUpdater(objMap,this);
           AllWorkersPanel.setVisible(true);
           NewupdatePanel(AllWorkersPanel);
           tw.populateallWorkersTable(objMap);
    }//GEN-LAST:event_AllWorkLabelMouseClicked

    private void newWorkerSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWorkerSaveButtonActionPerformed
        // TODO add your handling code here:
        String firstname = wkFirstNameTf.getText();
        String lastname = wkLastNameTF.getText();
        String phone = wkPhoneNumberTF.getText();
        String cell  = wkHomeCellJurisdictionTF.getText();
        String dept  = (String) deptregComboBox.getSelectedItem();
         if(!validated(firstname,lastname, phone,cell, dept)){JOptionPane.showMessageDialog(this, "Please Fill in all Compulsory Spaces");}
            else{       
           db.NewWorkersave(firstname,lastname, phone, cell, dept); 
        
        wkFirstNameTf.setText("");
        wkLastNameTF.setText("");
        wkHomeCellJurisdictionTF.setText("");
        wkPhoneNumberTF.setText("");
        deptregComboBox.setSelectedIndex(0);
         }
    }//GEN-LAST:event_newWorkerSaveButtonActionPerformed

    private void EnterworkfnamesearchTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EnterworkfnamesearchTFFocusLost
        // TODO add your handling code here:
            workfnameerrorlabel.setText(" ");
            workerrorimagefname.setIcon(null);
    }//GEN-LAST:event_EnterworkfnamesearchTFFocusLost

    private void EnterworklnamesearchTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EnterworklnamesearchTFFocusLost
        // TODO add your handling code here:
            worklnameerrorlabel.setText(" ");
            workerrorimagelnamelabel.setIcon(null);
    }//GEN-LAST:event_EnterworklnamesearchTFFocusLost

    private void SearchworkerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchworkerButtonActionPerformed
        // TODO add your handling code here:
        
        if (workfnamesearchRadioButton.isSelected())
        {
                String name = EnterworkfnamesearchTF.getText();
                HashMap<String, String[]> objMap =  db.getAworkerfname(name);
                 if (objMap.isEmpty())
                {
                    workfnameerrorlabel.setText("Please Enter the Correct First Name");
                    workerrorimagefname.setIcon(new javax.swing.ImageIcon("images/badsign.png"));
                }
                else
                 {
                   TabularRecordUpdater tw = new TabularRecordUpdater(objMap,this);
                   tw.populateOneWorkerTable(objMap); }
          }
        else if(worksearchnumberRadioButton.isSelected())
          {
                String dept = (String)deptsearchComboBox.getSelectedItem();
                HashMap<String, String[]> objMap =  db.getAworkerdept(dept);
                 if (objMap.isEmpty())
                {
                    depterrorlabel.setText("You Have No Member in this Department");
                    
                }
                else
                 {
                   TabularRecordUpdater tw = new TabularRecordUpdater(objMap,this);
                   tw.populateOneWorkerTable(objMap); }
           }
        else if (worksearchlnameRadioButton.isSelected())
        {
                String name = EnterworklnamesearchTF.getText();
                HashMap<String, String[]> objMap =  db.getAworkerlname(name);
                System.out.println(name);
                 if (objMap.isEmpty())
                {
                    worklnameerrorlabel.setText("Please Enter the Correct Last Name");
                    workerrorimagelnamelabel.setIcon(new javax.swing.ImageIcon("images/badsign.png"));
                }
                else
                 {
                   TabularRecordUpdater tw = new TabularRecordUpdater(objMap,this);
                   tw.populateOneWorkerTable(objMap); }
          }
    }//GEN-LAST:event_SearchworkerButtonActionPerformed

    private void NewWorkLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewWorkLabelMouseEntered
        // TODO add your handling code here:
            Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
            Object obj = evt.getSource();
            JLabel lb = (JLabel) obj;
            lb.setCursor(handCursor);
    }//GEN-LAST:event_NewWorkLabelMouseEntered
private boolean 
    validated(String firstname,String lastname, String phone, String cell, String dept)
      {
        if(firstname.isEmpty()||lastname.isEmpty()||phone.isEmpty()||cell.isEmpty()||dept.isEmpty())
        {
            return false;
        }
         return true;
      }

    public JTable getViewworkerTable() {
        return ViewworkerTable;
    }

    public JTable getAllworkersTable() {
        return allworkersTable;
    }
    
public void NewupdatePanel (JPanel currentPanel)
    {
        BackgroundPanel.removeAll();   
        GroupLayout l = (GroupLayout) BackgroundPanel.getLayout();   
        l.setHorizontalGroup(
            l.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        l.setVerticalGroup(
            l.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AllWorkLabel;
    private javax.swing.JPanel AllWorkersPanel;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JButton EditworkerSaveButton;
    private javax.swing.JTextField EnterworkfnamesearchTF;
    private javax.swing.JTextField EnterworklnamesearchTF;
    private javax.swing.JLabel NewWorkLabel;
    private javax.swing.JPanel NewWorkRegPanelIN;
    private javax.swing.JPanel NewWorkerRegPanel;
    private javax.swing.JButton SearchworkerButton;
    private javax.swing.JLabel ViewWorkLabel;
    private javax.swing.JPanel ViewWorkersPanel;
    private javax.swing.JTable ViewworkerTable;
    private javax.swing.JPanel WorkerHomepanel;
    private javax.swing.JTable allworkersTable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel depterrorlabel;
    private javax.swing.JComboBox deptregComboBox;
    private javax.swing.JComboBox deptsearchComboBox;
    private javax.swing.JLabel entermemberNumberlabel2;
    private javax.swing.JLabel entermemberNumberlabel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton newWorkerSaveButton;
    private javax.swing.JTextField wkFirstNameTf;
    private javax.swing.JTextField wkHomeCellJurisdictionTF;
    private javax.swing.JTextField wkLastNameTF;
    private javax.swing.JTextField wkPhoneNumberTF;
    private javax.swing.JLabel workerrorimagefname;
    private javax.swing.JLabel workerrorimagelnamelabel;
    private javax.swing.JButton workersBackbutton;
    private javax.swing.JLabel workfnameerrorlabel;
    private javax.swing.JRadioButton workfnamesearchRadioButton;
    private javax.swing.JLabel worklnameerrorlabel;
    private javax.swing.JRadioButton worksearchlnameRadioButton;
    private javax.swing.JRadioButton worksearchnumberRadioButton;
    // End of variables declaration//GEN-END:variables
}
